### ISSUE TITLE
非极大值抑制问题

### ISSUE THREAD

**Issue by Luoxiaoyu828** [Byronnar/tensorflow-serving-yolov3#105]
你好，yolo v3的代码我调通了，现在我想要实现一个功能是，
输入一个三维立方体数据:
(x,y,z)表示坐标点  d表示该坐标点上的强度   数据是网格化的结构  

输出数据中强度较高的区域位置 ，也即是用一个3D框将这个区域框出来

现在我遇到的问题是：非极大值抑制算法好像只支持2维图片的(我查了一下，不知道有没支持3维的)

请问有什么好的办法来解决一下吗？

**Comment by Luoxiaoyu828** [comment]
![image](https://user-images.githubusercontent.com/58614902/112825719-b03e7000-90be-11eb-8733-cb4907bf1588.png)
仿真数据是这样的

**Comment by Byronnar** [comment]
你好, 对于3D框的研究我也不是很了解哎,  一般情况下nms是支持二维的, 不过我建议你看一下3D目标检测的例子, 上面应该有类似NMS的操作的. 比如 CenterNet的3D检测部分.

**Comment by Luoxiaoyu828** [comment]
好的，谢谢你！
