### ISSUE TITLE
作者你好，使用visdrone数据集效果怎样，map能到多少

### ISSUE THREAD

**Issue by leiqing110** [Byronnar/tensorflow-serving-yolov3#106]
我使用yolov4训练visdrone数据集，map只有32.8，请问您训练的效果怎样呢

**Comment by Byronnar** [comment]
你好, visdrone 数据集数据不是很均衡, 而且有些目标比较小, 我记得当初训练效果也不是特别好, 加了一些其他tricks, 具体我忘了, map也是30多一点吧, 应该比yolov4还差点, 这个数据集可以试试two-stage 网络或者yolov5. 还可以增加一些数据增强.

**Comment by leiqing110** [comment]
> 你好, visdrone 数据集数据不是很均衡, 而且有些目标比较小, 我记得当初训练效果也不是特别好, 加了一些其他tricks, 具体我忘了, map也是30多一点吧, 应该比yolov4还差点, 这个数据集可以试试two-stage 网络或者yolov5. 还可以增加一些数据增强.

好谢谢了！

**Comment by Jackluisus** [comment]
可以试一下我的https://github.com/Jackluisus/VisDrone-ensemble-tensorflow，用二阶段模型的精度还好一些，官方指标ap_all 可以达到36多，感兴趣的话可以拿去改进，用些trick什么的，打visdrone的比赛应该是够了。
