### ISSUE TITLE
大佬，没看到有tmp文件夹啊

### ISSUE THREAD

**Issue by hablee** [Byronnar/tensorflow-serving-yolov3#107]
中间有一步是将生成的SavedModel文件夹放到tmp文件夹。但是我怎么没看到有这个文件夹？

**Comment by Byronnar** [comment]
请问你是什么系统?

**Comment by hablee** [comment]
> 请问你是什么系统?

win10，不过我在与yolov3平级下建了tmp文件夹，启动了tf-serving。用httpClient可以预测，grpc不行。报错信息时：
`Traceback (most recent call last):
  File "D:/projects/tensorflow-serving-yolov3/yolov3_tfserving/grpc_client.py", line 132, in <module>
    image = yolov3.predict( input_path, classes, threshold, output_path )
  File "D:/projects/tensorflow-serving-yolov3/yolov3_tfserving/grpc_client.py", line 90, in predict
    res = result_future.result()
  File "C:\Users\a\.conda\envs\tf1-yolov3\lib\site-packages\grpc\_channel.py", line 722, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1617699396.151000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5397,"referenced_errors":[{"created":"@1617699396.151000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>`

**Comment by Byronnar** [comment]
启动服务的时候暴露8500端口了么?  然后模型类别数, 代码里面图片分辨率是多少? 有没有做过什么修改.

**Comment by hablee** [comment]
> 启动服务的时候暴露8500端口了么? 然后模型类别数, 代码里面图片分辨率是多少? 有没有做过什么修改.

启动了，直接贴的您的代码`docker run -p 8501:8501 -p 8500:8500 --mount type=bind,source=D:/projects/tensorflow-serving-yolov3/savemodel/tmp/yolov3/,target=/models/yolov3 -e MODEL_NAME=yolov3 -t tensorflow/serving` 。代码里的参数我都没改。

**Comment by Byronnar** [comment]
你训练的tensorflow版本多少啊,  我没在windows系统测试过, 之前用的都是ubuntu, 不知道这个会不会有影响. 
```
details = "failed to connect to all addresses"
```
这个报错一般是你没把grpc端口暴露出来的. 仔细检查一下.

**Comment by hablee** [comment]
> 你训练的tensorflow版本多少啊, 我没在windows系统测试过, 之前用的都是ubuntu, 不知道这个会不会有影响.
> 
> ```
> details = "failed to connect to all addresses"
> ```
> 
> 这个报错一般是你没把grpc端口暴露出来的. 仔细检查一下.

谢谢大佬的回答，应该不是没有暴露的问题。我把grpc_client里面的server变量里面的0.0.0.0改成localhost就可以了

**Comment by Byronnar** [comment]
嗯嗯, 解决了问题就好, windows下面可能确实要这么改, 0.0.0.0是我在ubuntu环境下测试的, 而且localhost跟0.0.0.0也是有区别的.
