### ISSUE TITLE
批量图片测试

### ISSUE THREAD

**Issue by GitHubHuangxr** [Byronnar/tensorflow-serving-yolov3#11]
您好，请问你的批处理图片测试是怎么写的。我写的批处理图片处理，怎么生成结果的时间是单张处理的倍数。  谢谢

**Comment by Byronnar** [comment]
你可以看下我那个 images_demo_multi.py文件，你的批处理是每次预测都 加载了session，太耗时了，借鉴视频流一帧一帧处理，当做一次会话就会快很多。

**Comment by GitHubHuangxr** [comment]
好的谢谢， 您测试的FPS在1080上测试15-20帧！,是在Linux下运行的是吧？是使用什么GPU型号的，我用你的代码在windows上运行生成模型，608上测试每张0.18s左右。 windows比Linux慢那么多么？ 目前使用的电脑GPU是渣渣965M。

**Comment by Byronnar** [comment]
我的是 GTX1080啊，ubuntu上测试的，GeForce GTX 1080/PCIe/SSE2，在2080上更快.
你GPU确实 需要升级了

**Comment by mumu0419** [comment]
> 
> 
> 我的是 GTX1080啊，ubuntu上测试的，GeForce GTX 1080/PCIe/SSE2，在2080上更快.
> 你GPU确实 需要升级了

新手想请教一下，怎么测试模型的FPS？感谢
