### ISSUE TITLE
pb文件的大小并没有变化

### ISSUE THREAD

**Issue by huyi1989** [Byronnar/tensorflow-serving-yolov3#12]
减小的只是ckpt文件的大小，然而这个并没有什么大用，最终模型还是要量化成pb，但pb根本就没变化，所以显得有点多此一举，如果不改变结构的情况下去加深量化，可以将float32变为float16这样可以大幅度减少大小

**Comment by Byronnar** [comment]
如果要减小 PB大小确实可以试试你说的，也可以做模型剪枝。
中间ckpt减小一方面是为了节省磁盘体积，另一方面完全可以直接用 ckpt模型来预测啊，这又不难写，也没说一定要转换成PB模型预测。
你觉得没用可以不用。
