### ISSUE TITLE
打算用自己标注的训练集，训练自己的模型

### ISSUE THREAD

**Issue by sunanlin13174** [Byronnar/tensorflow-serving-yolov3#13]
作者你好，非常高兴看到汉字更多的出现在github上，感谢你的贡献，我会用自己的数据集进行训练，先好好学习下你的改进，过几天请教

**Comment by Byronnar** [comment]
谢谢你的肯定!

**Comment by sunanlin13174** [comment]
我在看generate_ancher.py这个文件，里面又划分了一次数据集吗？最后target_size有两种取值，针对YOLO3哪个更好呢？我现在看到了yolo2的论文，它是用416的训练的吧

**Comment by sunanlin13174** [comment]
> 谢谢你的肯定!

我用你的文件产生了自己的Anchors，但是我发现train.py里面没有用它啊~定义的类属性没有它好像，如何使用自己的Anchors到train.py呢

**Comment by Byronnar** [comment]
你好，Anchors 是在 config.py文件里面指定了的

**Comment by Byronnar** [comment]
416 608训练的都有

**Comment by sunanlin13174** [comment]
![image](https://user-images.githubusercontent.com/51011133/68828607-37b15c00-06e1-11ea-9502-77af6132fd82.png)
用自己的数据训练时报了这个error,已经修改了config中.names文件，求作者分析一下

**Comment by sunanlin13174** [comment]
[图片]txt如下

**Comment by sunanlin13174** [comment]
![image](https://user-images.githubusercontent.com/51011133/68828846-fcfbf380-06e1-11ea-919e-ba328f81e646.png)
txt如下

**Comment by sunanlin13174** [comment]
用你的code，根据数据集生成Anchors，类名也是自己的。然后先进行第一阶段的训练，正常进行；之后batch size 调到4，test size调到2,进行第二阶段的训练，然后就出现了这种情况，没报错，但是，，，，
![image](https://user-images.githubusercontent.com/51011133/68928893-19715c00-07c6-11ea-9422-4eebc5999ffb.png)
test loss : nan Saving.....
作者可知如何破？

**Comment by Byronnar** [comment]
Nan可能是学习率调太大了，这个你调小一下试试

**Comment by hqq1990** [comment]
想问下 想把学习率调小一点 是在哪里可以修改呢

**Comment by Byronnar** [comment]
学习率在 config.py文件里面
__C.TRAIN.LEARN_RATE_INIT       = 1e-4
__C.TRAIN.LEARN_RATE_END        = 1e-6

**Comment by hqq1990** [comment]
谢谢您的回复，如果要修改的话直接
_C.TRAIN.LEARN = 0.00025
这样可以吗？


Byronnar <notifications@github.com> 于2019年11月25日周一 下午9:04写道：
