### ISSUE TITLE
单目标训练效果差

### ISSUE THREAD

**Issue by tradysun** [Byronnar/tensorflow-serving-yolov3#14]
作者提到单目标分类准确率能达到70%，想知道那个工业检测数据集是公开的么？想试一下效果，因为我基于VOC2007数据集构造了多种文字类水印，按单分类的方式进行训练(4000张训练数据)，迭代了80个epoch，total loss能到1.2，但预测效果很差，基本得分都是0.3左右，mAP很低，感觉模型根本没收敛。

**Comment by tradysun** [comment]
![image](https://user-images.githubusercontent.com/24379156/68556486-7939d100-046d-11ea-9282-36d522219b97.png)

**Comment by Byronnar** [comment]
你数据集可能还得根据自己的特点修改参数，我那数据集不方便公开，但是那个时候训练了一百次，损失函数 0.7794, map的确很高，如果你方便可以把你的数据集给我训练一下。
我最近还训练了 安全帽检测，40轮，map也90多，不知道你是哪里出了问题。

**Comment by Byronnar** [comment]
不过，我数据集的量比你大，一万张，你看能不能做一下数据增增广

**Comment by sunanlin13174** [comment]
一定要进行第二阶段的训练，只进行第一阶段的训练效果很差的

**Comment by xxllp** [comment]
好奇 我单类几百张图片 需要迭代多少次 才好

**Comment by xxllp** [comment]
貌似可以了 真奇怪
