### ISSUE TITLE
自己的数据集对于anchor的大小如何选取

### ISSUE THREAD

**Issue by zhouxianming** [Byronnar/tensorflow-serving-yolov3#15]
你好。请问一下如果是自己的数据集和pascal数据集有点出路，是不是最好不要选用basline_anchors.txt中的anchor大小。我用您这个工程下的anchors_generate.py跑了一下自己的数据集，产生如下结果：
![2019-11-16 11-13-33屏幕截图](https://user-images.githubusercontent.com/49632230/68987176-33607c80-0862-11ea-8095-9f5b9d473f49.png)
请问是不是可以用：
[19.57, 17.0] [24.13, 24.33] [36.22, 19.20] [38.18, 29.15] [50.40,23.25]  [54.12,36.05] [ 71.02,28.26] [78.77,38.01] [88.0,55.68] 
来作为anchor呢？

**Comment by Byronnar** [comment]
你可以保留整数试试

**Comment by Byronnar** [comment]
我对 anchors脚本进行了 改进,可以生成直接可用的 anchors了,请看最新的那个文件.

**Comment by zhouxianming** [comment]
好的 感谢 我懂了

**Comment by zhouxianming** [comment]
@Byronnar
谢谢 我懂了。
我还有个问题请问下面代码，pred_sbbox、pred_mbbox、pred_lbbox大中小尺度下为什么都是19*19 不是应该19*19 38*38 76*76 吗？另外请问一下这个作用域有什么用吗？
/home/zxm/图片/2019-11-06 10-01-08屏幕截图.png

**Comment by zhouxianming** [comment]
@Byronnar
谢谢 我懂了。
我还有个问题请问下面代码，pred_sbbox、pred_mbbox、pred_lbbox大中小尺度下为什么都是1919 不是应该1919 3838 7676 吗？另外请问一下这个作用域有什么用吗？

  # hand-coded the dimensions: if 608, use 19; if 416, use 13
        with tf.variable_scope('pred_multi_scale'):
            self.pred_multi_scale = tf.concat([tf.reshape(self.pred_sbbox, [-1, 19, 19, 12]),
                                               tf.reshape(self.pred_mbbox, [-1, 19, 19, 12]),
                                               tf.reshape(self.pred_lbbox, [-1, 19, 19, 12])], axis=0, name='concat')
        # 说明,如果训练自己的数据集,将85改成 数据集里面的  类别数+5 ,再进行模型转化

**Comment by dodogoffy** [comment]
> 我对 anchors脚本进行了 改进,可以生成直接可用的 anchors了,请看最新的那个文件.

您好，我根据您提供的脚本生成直接可用的anchors了。

但是我看原本的baseline_anchors和coco_anchors之间是有个特征图尺度的缩放。
那我生成的anchors需要按照三个不同的尺度做相应的变化吗？

**Comment by Byronnar** [comment]
> @Byronnar
> 谢谢 我懂了。
> 我还有个问题请问下面代码，pred_sbbox、pred_mbbox、pred_lbbox大中小尺度下为什么都是1919 不是应该1919 3838 7676 吗？另外请问一下这个作用域有什么用吗？
> 
> # hand-coded the dimensions: if 608, use 19; if 416, use 13
> ```
>     with tf.variable_scope('pred_multi_scale'):
>         self.pred_multi_scale = tf.concat([tf.reshape(self.pred_sbbox, [-1, 19, 19, 12]),
>                                            tf.reshape(self.pred_mbbox, [-1, 19, 19, 12]),
>                                            tf.reshape(self.pred_lbbox, [-1, 19, 19, 12])], axis=0, name='concat')
>     # 说明,如果训练自己的数据集,将85改成 数据集里面的  类别数+5 ,再进行模型转化
> ```
我都设置成189是实验需要,这个 你试过改成 38 76 吗,应该也可以.
416 要用13的原因是:
这是因为检测的特征图有32倍的下采样，输入是416416的话，这里的特征图就是1313了
13×13×32×32 = 416×416

**Comment by Byronnar** [comment]
> > 我对 anchors脚本进行了 改进,可以生成直接可用的 anchors了,请看最新的那个文件.
> 
> 您好，我根据您提供的脚本生成直接可用的anchors了。
> 
> 但是我看原本的baseline_anchors和coco_anchors之间是有个特征图尺度的缩放。
> 那我生成的anchors需要按照三个不同的尺度做相应的变化吗？

不用,我用过coco_anchors.txt训练,效果也可以的.
我那个脚本是为了生成跟 coco_anchors差不多的.
你可以训练一下 对比效果

**Comment by dodogoffy** [comment]
> > > 我对 anchors脚本进行了 改进,可以生成直接可用的 anchors了,请看最新的那个文件.
> > 
> > 
> > 您好，我根据您提供的脚本生成直接可用的anchors了。
> > 但是我看原本的baseline_anchors和coco_anchors之间是有个特征图尺度的缩放。
> > 那我生成的anchors需要按照三个不同的尺度做相应的变化吗？
> 
> 不用,我用过coco_anchors.txt训练,效果也可以的.
> 我那个脚本是为了生成跟 coco_anchors差不多的.
> 你可以训练一下 对比效果

好哒！谢谢您！！！

**Comment by mumu0419** [comment]
> > > 我对 anchors脚本进行了 改进,可以生成直接可用的 anchors了,请看最新的那个文件.
> > 
> > 
> > 您好，我根据您提供的脚本生成直接可用的anchors了。
> > 但是我看原本的baseline_anchors和coco_anchors之间是有个特征图尺度的缩放。
> > 那我生成的anchors需要按照三个不同的尺度做相应的变化吗？
> 
> 不用,我用过coco_anchors.txt训练,效果也可以的.
> 我那个脚本是为了生成跟 coco_anchors差不多的.
> 你可以训练一下 对比效果

@Byronnar 你好，我的数据集图片分辨率是1240×375，检测物体像素占比和voc的也不一样，直接用anchor_generator.py生成了新的anchor（13,10, 21,15, 11,31, 39,17, 28,24, 54,29, 33,72, 86,48, 141,87），然后训练相同代数，检测效果不如用baseline_anchors.txt，差了四个百分点。是不是自己生成的anchor不合适？想知道怎么做比较好，非常感谢！
