### ISSUE TITLE
get the right target_size for prediction

### ISSUE THREAD

**Issue by kerolos** [Byronnar/tensorflow-serving-yolov3#17]
1- I would like to train my own dataset, so I used this script anchors_generate.py to get the right anchors in 416 X 416:  I got those values [189,189, 243,244, 276,275, 315,315, 397,261, 264,399, 367,367, 424,420, 556,564] , which is totaly deferent from orginal anchors (basline_anchors.txt) [1.25,1.625, 2.0,3.75, 4.125,2.875, 1.875,3.8125, 3.875,2.8125, 3.6875,7.4375, 3.625,2.8125, 4.875,6.1875, 11.65625,10.1875]. i would like to know which one should i used to get good result (my own anchors or basline_anchors)?  
2- for test part in config.py script, you used this value for the input_size 544 , which is  differnt from the input_size 608 in the image_demo.py. i would like to know which value i should ues for the input_size or i am free to choose any value in this array [320, 352, 384, 416, 448, 480, 512, 544, 576, 608] ?
3- the target input_size in anchors_generate.py should be the same as final input_size for prediction (testing) ?
thanks in advance Mr. @Byronnar :)

**Comment by Byronnar** [comment]
those values [189,189, 243,244, 276,275, 315,315, 397,261, 264,399, 367,367, 424,420, 556,564] is like coco_anchors.txt,  you  can compare them,  Use this is ok.
In my opinion, using the default anchors is enough great unless your datasets are really different from voc or coco datasets.

**Comment by kerolos** [comment]
thanks a lot, Mr @Byronnar for your quick reply, I really appreciate that.
- Could you inform me which size I should use for prediction 416, or 544 or 608?
 - I also displayed the small, medium, and large predictions (pred_sbbox, pred_mbbox, pred_lbbox ) before concatenation. I found that only the pred_mbbox has the correct prediction information than others. do I need this concatenation?

**Comment by Byronnar** [comment]
Yes, you need this concatenation because I have use three strides,        
with tf.variable_scope('pred_sbbox'):
            self.pred_sbbox = self.decode(self.conv_sbbox, self.anchors[0], self.strides[0])
 with tf.variable_scope('pred_mbbox'):
            self.pred_mbbox = self.decode(self.conv_mbbox, self.anchors[1], self.strides[1])
with tf.variable_scope('pred_lbbox'):
            self.pred_lbbox = self.decode(self.conv_lbbox, self.anchors[2], self.strides[2])
These can make better performance together.
The size depend on your image original size.608 is better for many situation.
