### ISSUE TITLE
请问为什么下载的预训练模型用不了啊？

### ISSUE THREAD

**Issue by huolianchu** [Byronnar/tensorflow-serving-yolov3#18]
训练的时候会打印模型不存在，直接对预训练模型进行转化的话，读取为空

**Comment by Byronnar** [comment]
先用convert_weights.py转化,再用freeze.py

**Comment by huolianchu** [comment]
> 先用convert_weights.py转化，再用freeze.py

非常感谢您的回复，我在使用convert_weights.py转化的时候，load = tf.train.import_meta_graph(org_weights_path + '.meta')
这一句读取为空，地址再三确认没有问题，您有遇到过这种情况吗

**Comment by Byronnar** [comment]
这个我没有遇到过哎.我等下上传一个转化好的放到上面吧

**Comment by huolianchu** [comment]
> 这个我没有遇到过哎。我等下上传一个转化好的放到上面吧

谢谢大佬，没有预训练模型从头开始训练太难收敛了，数据集不够

**Comment by Byronnar** [comment]
> > 这个我没有遇到过哎。我等下上传一个转化好的放到上面吧
> 
> 谢谢大佬，没有预训练模型从头开始训练太难收敛了，数据集不够

已经上传了，你看一下最新README

**Comment by huolianchu** [comment]
> > > 这个我没有遇到过哎。我等下上传一个转化好的放到上面吧
> > 
> > 
> > 谢谢大佬，没有预训练模型从头开始训练太难收敛了，数据集不够
> 
> 已经上传了，你看一下最新README



> > > 这个我没有遇到过哎。我等下上传一个转化好的放到上面吧
> > 
> > 
> > 谢谢大佬，没有预训练模型从头开始训练太难收敛了，数据集不够
> 
> 已经上传了，你看一下最新README

已经愉快的开始跑训练了，谢谢大佬
