### ISSUE TITLE
仓主救命，请问我用split.py文件进行训练集和测试集的划分之后，为什么没有产生包含图像坐标、尺寸的train.txt文件呢

### ISSUE THREAD

**Issue by lw17809213284** [Byronnar/tensorflow-serving-yolov3#19]

**Comment by lw17809213284** [comment]
2.2产生训练数据txt文件

$ python split.py
train.txt里面应该像这样：xxx / xxx.jpg 18.19,6.32,424.13,421.83,20 323.86,2.65,640.0,421.94,20 xxx / xxx.jpg 48,240,195,371,11 8,12,352,498,14 image_path x_min，y_min，x_max ，y_max，class_id x_min，y_min，...，class_id x_min，y_min等。对应于XML文件中的数据

就是上面这句话

**Comment by Byronnar** [comment]
产生了 2007_train.txt这样的文件吧? 用那个就好.
