### ISSUE TITLE
模型体积减小三分之二是怎么做到的？

### ISSUE THREAD

**Issue by zpge** [Byronnar/tensorflow-serving-yolov3#2]
Rt

**Comment by Byronnar** [comment]
你好，之所以有900M，是因为tf.train.ExponentialMovingAverage（）这个函数，它会是生成等量的tf.trainable_variable()，保存到tf.global_variables()，而ckpt保存的主要是tf.trainable_variable（还有untrainable，但太小），所以ckpt的大小会翻倍；
为了不报找不到预训练模型的错，这里我做了改动，而且对位置进行了调整。

**Comment by ChunmianLin** [comment]
你好，能具体说下你做的改动吗？我看了下tf.train.ExponentialMovingAverage（）部分，好像没啥变化(跟YunYang那个相比)。还有个问题就是在代码中你怎么计算模型的大小以及测试的fps，我找不到具体的对应。
感谢！

**Comment by Byronnar** [comment]
> 你好，能具体说下你做的改动吗？我看了下tf.train.ExponentialMovingAverage（）部分，好像没啥变化(跟YunYang那个相比)。还有个问题就是在代码中你怎么计算模型的大小以及测试的fps，我找不到具体的对应。
> 感谢！

你好，改动的主要是with tf.name_scope('loader_and_saver'):这个部分，去除了一些不需要恢复的层，not　in 实现，并且把位置提前了，不会重复计算。
计算模型大小，你跑下ＹＵＹＡＮＧ模型看下大小，再跑下我模型训练自己数据集看下模型大小不就知道了吗？
测试ＦＰＳ我加到代码里面了，通过ｍｓ换算成帧率就好啦。

**Comment by ChunmianLin** [comment]
感谢回复！我再具体地看下with tf.name_scope('loader_and_saver'):这个部分。至于第二个问题，你没明白我说的意思。我是想表达，在你的代码中哪个部分是计算模型大小的，我项计算下模型但是没找到。最后，测试的fps是在evaluate代码中吗？
感谢！

**Comment by Byronnar** [comment]
我没有特意在代码里面计算模型大小，对保存权重，位置这些做了调整，然后，ｆｐｓ测试实在video_demo.py文件里面。测试一下视频就可以看到了。

**Comment by ChunmianLin** [comment]
> 我没有特意在代码里面计算模型大小，对保存权重，位置这些做了调整，然后，ｆｐｓ测试实在video_demo.py文件里面。测试一下视频就可以看到了。

所以你所说的模型体积减少三分之二的意思：你保存的模型，跟YunYang中保存的模型的大小对比，减少了三分之二，可以这么理解吗？
fps我再具体看下代码过程，想再问一句就是你这儿的fps就是标准的计算fps的方式，对吗？
感谢答复！

**Comment by Byronnar** [comment]
模型大小可以这么理解，如果还需要更具体的定量分析，可以尝试做模型剪枝，后期我可能会做一下。
计算ｆｐｓ用的是主流方法，计算的是ms再换算成　ＦＰＳ

**Comment by ChunmianLin** [comment]
> 模型大小可以这么理解，如果还需要更具体的定量分析，可以尝试做模型剪枝，后期我可能会做一下。
> 计算ｆｐｓ用的是主流方法，计算的是ms再换算成　ＦＰＳ

清楚明白了，具体的细节我啃代码去。感谢！
