### ISSUE TITLE
训练私有数据集

### ISSUE THREAD

**Issue by HaiLongEmb** [Byronnar/tensorflow-serving-yolov3#21]
感谢作者的分享

这里有个小问题想咨询作者，我看到介绍训练的过程是1、下载预训练模型。2、准备训练数据。并修改confi.py  3、python convert_weight.py  4、python train.py 最后5、python freeze_graph.py进行测试。
但我看YunYang再进行迁移训练的时候是python convert_weight.py --train_from_coco，请问这样有什么不同，这部分代码没有看明白，
        if flag.train_from_coco:
            if (var_name_mess[-1] not in ['weights', 'gamma', 'beta', 'moving_mean', 'moving_variance']) or \
                    (var_name_mess[1] == 'yolo-v3' and (var_name_mess[-2] in preserve_org_names)): continue
希望作者能指点一下

**Comment by Byronnar** [comment]
这是因为我们用这个预训练模型做fine tuning的时候 只需要恢复特定的层,不需要全部的, 不然会报错的.因为你训练的不是同一个数据集

**Comment by HaiLongEmb** [comment]
@Byronnar 感谢你的回答，做fine tuning的时候数据集不能有较大改变，类别和anchors都不能变，只能增加测试图片，这时python convert_weight.py只恢复特定的层即可继续训练。
但如果更换数据集，类别和anchors都改变，需要python convert_weight.py --train_from_coco，才能继续训练新数据集，这样理解对吗？
