### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Mrdwq** [Byronnar/tensorflow-serving-yolov3#22]
![image](https://user-images.githubusercontent.com/49830883/69597439-f30eb480-1040-11ea-9003-1e15b47057d8.png)
core文件夹下的dataset.py对bbox_xywh做了scale
bbox_xywh_scaled = 1.0 * bbox_xywh[np.newaxis, :] / self.strides[:, np.newaxis]
那生成的anchor是不是也要scale一下才能算两者之间的IoU? 就是scale成baseline_anchors.txt文件中那样。
anchors_xywh[:, 2:4] = self.anchors[i]
 iou_scale = self.bbox_iou(bbox_xywh_scaled[i][np.newaxis, :], anchors_xywh)

**Comment by Byronnar** [comment]
我试过直接用 coco_anchors效果也很不错。那个是没有缩放的。
你对比了吗？

**Comment by Mrdwq** [comment]
我用baseline_anchors试了一下，发现效果没coco_anchors好。
还有就是我用下面的配置训练voc2007trainval和2012trainval组成的训练集，用voc2007test做测试，发现会出现过拟合。我把最好的测试集效果的模型保存下来，测试集损失为5.9822，mAP为76%，请问有什么方法能进一步降低测试集损失，提高mAP。训练集与测试集用scripts下的voc_anotation生成。
配置信息:
__C.YOLO.CLASSES                = "./data/classes/voc.names"
__C.YOLO.ANCHORS                = "./data/anchors/coco_anchors.txt"
__C.YOLO.MOVING_AVE_DECAY       = 0.999
__C.YOLO.STRIDES                = [8, 16, 32]
__C.YOLO.ANCHOR_PER_SCALE       = 3
__C.YOLO.IOU_LOSS_THRESH        = 0.5
__C.YOLO.UPSAMPLE_METHOD        = "resize"
__C.YOLO.ORIGINAL_WEIGHT        = "./checkpoint/yolov3_coco.ckpt"
__C.YOLO.DEMO_WEIGHT            = "./checkpoint/yolov3_coco_demo.ckpt"

__C.TRAIN.ANNOT_PATH            = "./data/dataset/voc_train.txt"
__C.TRAIN.BATCH_SIZE            = 8
__C.TRAIN.INPUT_SIZE            = [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
# __C.TRAIN.INPUT_SIZE          = [416]
__C.TRAIN.DATA_AUG              = True
__C.TRAIN.LEARN_RATE_INIT       = 2e-4
__C.TRAIN.LEARN_RATE_END        = 1e-6
__C.TRAIN.WARMUP_EPOCHS         = 2
__C.TRAIN.FISRT_STAGE_EPOCHS    = 20
__C.TRAIN.SECOND_STAGE_EPOCHS   = 30
__C.TRAIN.INITIAL_WEIGHT        = "./checkpoint/yolov3_coco_demo.ckpt"

# __C.TEST.ANNOT_PATH             = "./data/dataset/val.txt"
__C.TEST.ANNOT_PATH             = "./data/dataset/voc_test.txt"
__C.TEST.BATCH_SIZE             = 2
__C.TEST.INPUT_SIZE             = 544
__C.TEST.DATA_AUG               = False
__C.TEST.WRITE_IMAGE            = True
__C.TEST.WRITE_IMAGE_PATH       = "./data/detection/"
__C.TEST.WRITE_IMAGE_SHOW_LABEL = True
__C.TEST.WEIGHT_FILE            = "./checkpoint/yolov3_val_loss=5.9822.ckpt-34"
__C.TEST.SHOW_LABEL             = True
__C.TEST.SCORE_THRESHOLD        = 0.3
__C.TEST.IOU_THRESHOLD          = 0.45
