### ISSUE TITLE
实时性问题

### ISSUE THREAD

**Issue by HaiLongEmb** [Byronnar/tensorflow-serving-yolov3#23]
你好作者，请问你用TensorFlow-serving部署后，通过post请求这种方式实时性能达到多少fps，还有如果我为了高实时性部署到本地，除了TensorFlow-serving还有其他部署方式吗？我现在使用pyinstaller进行打包，不知道这种方式效率与TensorFlow-serving差别大吗？

**Comment by Byronnar** [comment]
fps你得看 部署到哪里，然后是什么设备。
提高实时性，感觉可能得牺牲精度，这个项目只是提供了一个思路， 可以设计一个 tiny网络，再用serving
其他部署方式 可以尝试 tflite移植到 移动端。
pyinstaller打包不太熟悉哎，跟我们服务器部署不一样
