### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by MC1016** [Byronnar/tensorflow-serving-yolov3#25]
您好，麻烦问一下现在的模型在windows上能跑吗？

**Comment by Byronnar** [comment]
windows还没试过. 不过,理论上只要你windows 环境配好了.比如 驱动, CUDA等, 也同样可以跑的, 因为我参数也没使用 命令行形式

**Comment by MC1016** [comment]
我环境搭建好了，想在您的这个版本上训练自己的xml数据，直接把对应的标签文件放进VOC文件里就可以了吗？

**Comment by Byronnar** [comment]
是的,xml文件 跟 jpg文件放到对应文件夹, 然后按照readme修改类别就好

**Comment by MC1016** [comment]
博主您好，麻烦问一下能否将自己训练完成以后的模型中的卷积参数提取出来？ 就像权重偏置，以及BN层的参数？
