### ISSUE TITLE
原理请教

### ISSUE THREAD

**Issue by HaiLongEmb** [Byronnar/tensorflow-serving-yolov3#26]
你好作者：
           有个细节理解不到位，在训练和验证的时候都是使用opencv读取图片，并且将格式从BGR转到RGB，那如果不进行转换有没有问题，在训练的时候我就使用BGR格式的数据，验证的时候也是BGR。我想不出为什么不行，我看到别人yolov3的复现都是用RGB，都没讲BGR为什么不行。
          请作者指教，也欢迎各位提出自己的想法。

**Comment by Byronnar** [comment]
你好,我觉得 这是跟opencv处理图像有关的,  我查了一下, opencv默认通道是bgr的, bgr是个历史遗留问题，为了兼容早年的某些硬件。其实你自己训练完全可以用rgb，新库也基本没了bgr还是rgb这个问题，就是切换下顺序。但如果你要用一些老的训练好的模型，就得兼容老模型的bgr。
我最后生成图片结果 转换成RGB是为了 看着好一些(色彩不会变)
