### ISSUE TITLE
网络结构修改

### ISSUE THREAD

**Issue by zoroyihan** [Byronnar/tensorflow-serving-yolov3#27]
请问作者对于原版Tensorflow-yolov3的网络结构具体做了哪些修改呢

**Comment by Byronnar** [comment]
主要是 是为了 部署服务修改了输出那里的网络,后面会添加一个 mobilenetv2的网络.

**Comment by zoroyihan** [comment]
请问如何修改能实现在第一阶段冻结训练和第二阶段解冻训练使用不同的batch size呢，因为第一阶段应该可以用更大batch_size才对吧

**Comment by Byronnar** [comment]
这个你可以加一个参数, 然后 修改datasets.py文件,  主要要修改数据批处理操作,这里改好之后 ,在train.py里面加一个判断, 就像学习率那样,
       # 阶段学习率
        for epoch in range(1, 1 + self.first_stage_epochs + self.second_stage_epochs):
            if epoch <= self.first_stage_epochs:
                train_op = self.train_op_with_frozen_variables
            else:
                train_op = self.train_op_with_all_variables
思路是这样,具体做起来可能有点麻烦, 你有时间可以自己尝试一下

**Comment by zoroyihan** [comment]
谢谢啦，在看到你的回答之前自己改好了，和你说的一样

**Comment by Byronnar** [comment]
> 谢谢啦，在看到你的回答之前自己改好了，和你说的一样

你好,你介意发一个 pull requests 改进一下这个仓库代码嘛,大家一起学习, 不知道改了之后效果是不是会好一些.
