### ISSUE TITLE
日志文件

### ISSUE THREAD

**Issue by MC1016** [Byronnar/tensorflow-serving-yolov3#28]
博主您好，自己训练完成以后再log文件下生成的是自己训练的日志文件吗？一般不应该是.log的格式，我训练完以后是event这种形式？

**Comment by Byronnar** [comment]
是event形式,也可以通过 tensorboard查看,不影响

**Comment by MC1016** [comment]
您好博主。我用tensorboard 指令查看event文件，只能显示我的结构图呀，loss iou 这些曲线在哪里可以查到？一直没有在生成的网页里找到

**Comment by Byronnar** [comment]
你是不是哪里写错了,我的有的啊,刚刚还试了下,可以看到
用指令
tensorboard  --logdir=your path/data/log

**Comment by MC1016** [comment]
我对您的代码没有大的修改，只是修改了一下路径和分类数量，不应该有影响呀，您方便在线指导一下我吗？

**Comment by Byronnar** [comment]
我可能知道了, 你tensorboard 打开网页之后,找到 左上角的 SCALARS (在 GRAPH的旁边),切换一下就好了
