### ISSUE TITLE
前辈，请问对于计算mAP的那个main代码，有没有详细的注释，我想在一个图上同时显示训练好的两个模型的AP曲线，请问如何修改，我尝试过还是没改好，希望您能指点我，感谢您的回复

### ISSUE THREAD

**Issue by lw17809213284** [Byronnar/tensorflow-serving-yolov3#29]

**Comment by Byronnar** [comment]
你好，这个 你主要是哪里遇到了问题？  
理论上已经生成了 groud truth跟预测结果是可以画曲线的，不过我也还没测试

**Comment by lw17809213284** [comment]
谢谢前辈回复，我现在是通过两个不同的YOLOv3模型使用同样的测试集运行evaluate文件得到了两组ground-truth和predicted的值，现在想通过main文件生成AP曲线，且一张图上要同时生成这两组值对应的两条曲线
