### ISSUE TITLE
ExponentialMovingAverage

### ISSUE THREAD

**Issue by robinjoe93** [Byronnar/tensorflow-serving-yolov3#3]
在train.py中，
with tf.name_scope('loader_and_saver')放在with tf.name_scope('define_weight_decay')前面，在evaluate.py的时候，不会出现找不到，../../ExponentialMovingAverage的错误吗

**Comment by Byronnar** [comment]
我没有碰到这个问题啊，运行的是我仓库里　result_evaluate文件，你训练好自己数据集了吗．

**Comment by robinjoe93** [comment]
> 我没有碰到这个问题啊，运行的是我仓库里　result_evaluate文件，你训练好自己数据集了吗．
我是训练了自己的训练集。       我看了一下，仓库里好像没有你说的这个result_evaluate文件，但咱们的evaluate文件是一样的，我自己用的时候是要把我问题中的两个空间调一下位置，再evaluate的时候才不会报错。

**Comment by robinjoe93** [comment]
> 我没有碰到这个问题啊，运行的是我仓库里　result_evaluate文件，你训练好自己数据集了吗．

我是训练了自己的训练集。       我看了一下，仓库里好像没有你说的这个result_evaluate文件，但咱们的evaluate文件是一样的，我自己用的时候是要把我问题中的两个空间调一下位置，再evaluate的时候才不会报错。

**Comment by Byronnar** [comment]
是的，我那个文件名字上传的时候改回来了。
调换一下就可以evaluate有影响结果嘛？我刚刚评估的好像是　之前９００m的模型，新模型没用ｅｖａｌｕａｔｅ文件测试，你可以对比一下。

**Comment by robinjoe93** [comment]
> 是的，我那个文件名字上传的时候改回来了。
> 调换一下就可以evaluate有影响结果嘛？我刚刚评估的好像是　之前９００m的模型，新模型没用ｅｖａｌｕａｔｅ文件测试，你可以对比一下。

就是不调换是会报错，说是找不到ExponentialMovingAverage 这个参数，这个参数是再yolov3定义模型的时候，在bn层中定义的一个指数滑动平均，是可以训练的，所以在global_variables的时候，会把这部分参数加入到ckpt文件中。
以上是我个人的理解，具体正确与否还需要商榷

**Comment by Byronnar** [comment]
嗯，好的，谢谢指出，我有时间也再研究一下。

**Comment by Byronnar** [comment]
> > 是的，我那个文件名字上传的时候改回来了。
> > 调换一下就可以evaluate有影响结果嘛？我刚刚评估的好像是　之前９００m的模型，新模型没用ｅｖａｌｕａｔｅ文件测试，你可以对比一下。
> 
> 就是不调换是会报错，说是找不到ExponentialMovingAverage 这个参数，这个参数是再yolov3定义模型的时候，在bn层中定义的一个指数滑动平均，是可以训练的，所以在global_variables的时候，会把这部分参数加入到ckpt文件中。
> 以上是我个人的理解，具体正确与否还需要商榷

你好，今天测试了一下，确实 with tf.name_scope('loader_and_saver'): 这一步要放到 with tf.name_scope("define_weight_decay"): 这一步下面，现在可以直接进行评估了，模型体积相对于原来YUYANG大神的还是减小了二分之一。你可以用最新的代码测试。
