### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by mumu0419** [Byronnar/tensorflow-serving-yolov3#30]
前辈你好，我刚开始学这个，想请教一下如果想测模型的检测速度，要怎么做？

**Comment by Byronnar** [comment]
你好，下载预训练模型 ，转化好， 把视频放到指定位置， 修改视频路径，  运行 python video_demo.py,  会显示 当前测试视频的 FPS跟TIMES

**Comment by mumu0419** [comment]
感谢解答！那如果想测单张图片的检测时间要怎么实现呢？

**Comment by Byronnar** [comment]
time模块，不过测试一张图片，加载环境可能要几秒种，测试多张图片快一些
