### ISSUE TITLE
大神,啥时候添加moblienetv2呢?

### ISSUE THREAD

**Issue by alwan1989** [Byronnar/tensorflow-serving-yolov3#34]
如题,感谢你的辛劳付出,还有个问题,代码如何支持断点训练呢?或者训练了很久了,重新再次加载训练?

**Comment by alwan1989** [comment]
你的代码训练完成后,例如生成一个loss2.05的ckpt文件,但重新加载这个ckpt来训练,损失很大,相当于重新训练了,就算把第一阶段的学习率调节得很小,损失还是很大^^^^^^^

**Comment by Byronnar** [comment]
mobelnet v2版本已经可以训练了，不过还不可以用来演示，没放上来，，最近没时间。。

**Comment by Byronnar** [comment]
关于二次训练我还没做，你损失很大是直接 改了config文件继续训练？

**Comment by alwan1989** [comment]
是的,我直接将初始化加载ckpt文件那里,改成已经训练好的ckpt^^^^^^^^^但损失很大,相当于重新开始训练了,但几个epchod后损失降得很快(感觉比随机初始化的损失要快一点点)

**Comment by alwan1989** [comment]
请问下,你的moblienetv2主干网放在哪呢?为啥我找不到^^

**Comment by Byronnar** [comment]
> 请问下,你的moblienetv2主干网放在哪呢?为啥我找不到
我還沒放到 github倉庫上面, 還沒調整好

**Comment by Byronnar** [comment]
> 请问下,你的moblienetv2主干网放在哪呢?为啥我找不到^^

@alwan1989 ，你好， moblienetv2 已经上传仓库了， 目前支持训练，模型90多m， 你可以看一下

**Comment by largeword** [comment]
这个用pytorch写的yolov3支持继续训练，可以参考一下https://github.com/FLyingLSJ/Computer_Vision_Project/tree/master/Object_Detection/yolo_demo/PyTorch-YOLOv3-master
