### ISSUE TITLE
请教，输入尺寸问题

### ISSUE THREAD

**Issue by HaiLongEmb** [Byronnar/tensorflow-serving-yolov3#36]
你好,请教一个原理问题，我看到yolov3有三个出入张量版本，320,416，和608。
我理解不同的输入张量大小对应的耗时时间不同，我想问题的是为什么不能是640*640,或者其他的尺寸。640同样能被32整除啊。而且我强制使用640*640进行训练，训练后的模型也可以使用。

请问您是如何理解这个问题的。

**Comment by Byronnar** [comment]
只要是 32的倍数就可以了, 没有 320 416 608 限制

**Comment by HaiLongEmb** [comment]
感谢您的回答，最后一个问题，我看你代码中有这段：
# hand-coded the dimensions: if 608, use 19; if 416, use 13
        with tf.variable_scope('pred_multi_scale'):
            self.pred_multi_scale = tf.concat([tf.reshape(self.pred_sbbox, [-1, 19, 19, 3]),
                                               tf.reshape(self.pred_mbbox, [-1, 19, 19, 3]),
                                               tf.reshape(self.pred_lbbox, [-1, 19, 19, 3])], axis=0, name='concat')

请问这是修改的模型那部分结构，我理解如果只是改输入尺寸，单纯input层改变一下就行了应该。

**Comment by Byronnar** [comment]
这个你自己定义,可以尝试一下
