### ISSUE TITLE
 用自己的model预测时，调用serving api出现reshape error# {'error': 'Input to reshape is a tensor with 6498 values, but the requested shape requires a multiple of 30685\n\t [[{{node pred_multi_scale/Reshape_2}}]]'}    

### ISSUE THREAD

**Issue by netist123** [Byronnar/tensorflow-serving-yolov3#37]
用自己的model预测时，调用serving api出现reshape error# {'error': 'Input to reshape is a tensor with 6498 values, but the requested shape requires a multiple of 30685\n\t [[{{node pred_multi_scale/Reshape_2}}]]'}    

我看到yolov3_api.py里也有类似注释，看来作者也出现了这样的问题，请问是怎么解决的呢？

训练出来的模型是85个维度吗？ （19 * 19 * （80+1+4））=30685
我的class只有一类。

**Comment by netist123** [comment]
貌似是不是必须要修改config目录里的yolov3.py?


        with tf.variable_scope('pred_multi_scale'):
            self.pred_multi_scale = tf.concat([tf.reshape(self.pred_sbbox, [-1, 19, 19, 85]),
                                               tf.reshape(self.pred_mbbox, [-1, 19, 19, 85]),
                                               tf.reshape(self.pred_lbbox, [-1, 19, 19, 85])], axis=0, name='concat')

这里的‘85’是不是都要改成self.num_class+5 ?
然后再训练，再转换成可部署的模型？

**Comment by Byronnar** [comment]
是必须修改 yolov3.py文件的 , 修改之后就可以了

**Comment by netist123** [comment]
> 是必须修改 yolov3.py文件的 , 修改之后就可以了

非常感谢。解决了！
