### ISSUE TITLE
大佬你好，关于GPU训练时利用率低的问题

### ISSUE THREAD

**Issue by largeword** [Byronnar/tensorflow-serving-yolov3#38]
我用2080ti训练时，显卡的利用率特别低，总体功耗情况和任务管理器里面显示的cuda占用情况差不多，驱动和cuda都是最新版本的，tf为1.15版本，我设置batch size为32，训练样本大概为6500个，一共分两类。请问这是什么问题？或者说要怎么提高效率？
![批注 2019-12-21 021625](https://user-images.githubusercontent.com/16517736/71281111-1571c480-2398-11ea-9df8-7ad525bdae60.jpg)

**Comment by Byronnar** [comment]
你这是在 windows下面训练的吧， 我查过，他那个gpu利用率显示就是有些问题，我再ubuntu下训练，利用率都是百分之90多的。

**Comment by largeword** [comment]
感谢回复，如果只是利用率显示有问题，那为什么evga自带的显卡管理软件显示的功耗也有问题？显卡功耗比例和利用率显示的差不多。是不是在windows下这两项都有问题？



---原始邮件---
发件人: "Byronnar"<notifications@github.com&gt;
发送时间: 2019年12月21日(周六) 上午8:44
收件人: "Byronnar/tensorflow-serving-yolov3"<tensorflow-serving-yolov3@noreply.github.com&gt;;
抄送: "largeword"<1209425127@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Byronnar/tensorflow-serving-yolov3] 大佬你好，关于GPU训练时利用率低的问题 (#38)



你这是在 windows下面训练的吧， 我查过，他那个gpu利用率显示就是有些问题，我再ubuntu下训练，利用率都是百分之90多的。

**Comment by mumu0419** [comment]
请问问题解决了吗？我的GPU利用率也是很低

**Comment by largeword** [comment]
换到linux系统，显卡利用率果然很不错，应该是某些库在windows下的特定问题



---原始邮件---
发件人: "wangsen"<notifications@github.com&gt;
发送时间: 2020年1月3日(周五) 下午4:59
收件人: "Byronnar/tensorflow-serving-yolov3"<tensorflow-serving-yolov3@noreply.github.com&gt;;
抄送: "largeword"<1209425127@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Byronnar/tensorflow-serving-yolov3] 大佬你好，关于GPU训练时利用率低的问题 (#38)



请问问题解决了吗？我的GPU利用率也是很低

**Comment by mumu0419** [comment]
> 换到linux系统，显卡利用率果然很不错，应该是某些库在windows下的特定问题
> […](#)
> ---原始邮件--- 发件人: "wangsen"<notifications@github.com&gt; 发送时间: 2020年1月3日(周五) 下午4:59 收件人: "Byronnar/tensorflow-serving-yolov3"<tensorflow-serving-yolov3@noreply.github.com&gt;; 抄送: "largeword"<1209425127@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [Byronnar/tensorflow-serving-yolov3] 大佬你好，关于GPU训练时利用率低的问题 (#38) 请问问题解决了吗？我的GPU利用率也是很低 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这样啊，感谢回复
