### ISSUE TITLE
precision、recall问题

### ISSUE THREAD

**Issue by dodogoffy** [Byronnar/tensorflow-serving-yolov3#39]
想请问一下，如果想在这版代码加上算precision、recall的代码要怎么加？自己尝试着加了，但是毫无头绪。谢谢您！

**Comment by Byronnar** [comment]
main.py里面 把fp tp这些指标都求出来了, 只要根据这些指标不久可以求 precision、recall了么

**Comment by dodogoffy** [comment]
> main.py里面 把fp tp这些指标都求出来了, 只要根据这些指标不久可以求 precision、recall了么

好的！谢谢啊！

**Comment by Byronnar** [comment]
> > main.py里面 把fp tp这些指标都求出来了, 只要根据这些指标不久可以求 precision、recall了么
> 
> 好的！谢谢啊！

把代码加在这里就好了:
with open(results_files_path + "/results.txt", 'a') as results_file:
  results_file.write("\n# Number of predicted objects per class\n")
  for class_name in sorted(pred_classes):
    n_pred = pred_counter_per_class[class_name]
    text = class_name + ": " + str(n_pred)
    text += " (tp:" + str(count_true_positives[class_name]) + ""
    text += ", fp:" + str(n_pred - count_true_positives[class_name]) + ")\n"
    results_file.write(text)

    tp_value = str(count_true_positives[class_name])
    fp_value = str(n_pred - count_true_positives[class_name])
    fn_value = int(str(gt_counter_per_class[class_name])) - int(tp_value)

    print('tp-----:', tp_value)
    print('fp-----:', fp_value)
    print('fn-----:', fn_value)

    precision = float(int(tp_value) / (int(str(tp_value)) + int(str(fp_value))))
    recall = float(int(tp_value) / (int(str(tp_value)) + int(str(fn_value))))

    print('precision:',class_name,precision)
    print('recall:', class_name, recall)
@dodogoffy
