### ISSUE TITLE
有尝试convert pb to tensorlflowlite 吗？

### ISSUE THREAD

**Issue by CharonMing** [Byronnar/tensorflow-serving-yolov3#40]

**Comment by Byronnar** [comment]
转是转了,但是模型体积没减小..有些问题

**Comment by CharonMing** [comment]
> 转是转了,但是模型体积没减小..有些问题

对，我也测试过了，量化后体积减少到1/4左右，但是android端巨慢，没有非量化后快。

**Comment by dodogoffy** [comment]
> > 转是转了,但是模型体积没减小..有些问题
> 
> 对，我也测试过了，量化后体积减少到1/4左右，但是android端巨慢，没有非量化后快。

您好，想和你请教一下，如何转化成tensorflow lite 谢谢！
