### ISSUE TITLE
修改了网络结构，重头开始训练的问题。

### ISSUE THREAD

**Issue by dodogoffy** [Byronnar/tensorflow-serving-yolov3#41]
您好，我想请问一下我修改了YOLOv3的主干特征网络，无法使用coco的预训练权重，直接重头训练100epoch，这样子的效果并没有原始的YOLOv3代码加载coco的预训练权重进行两个stage（20+30）训练的效果好。我不确定这是由于我没有加载coco的预训练权重造成的，还是因为我添加的block起了反效果？请问您可以给我一些建议吗？（谢谢你啊！你是唯一一个会回复我的人！！）

**Comment by Byronnar** [comment]
请问你是修改成了什么网络呢?   训练的什么类别?
一般来说,不加载预训练模型更难收敛,你这情况也正常

**Comment by dodogoffy** [comment]
> 请问你是修改成了什么网络呢? 训练的什么类别?
> 一般来说,不加载预训练模型更难收敛,你这情况也正常

我是在darknet53backbone添加了一些注意力block，训练的类别是道路目标。

**Comment by anmochen** [comment]
你好，我训练的时候，出现了这个问题：NotImplementedError: Can not build up yolov3 network!
请问你训练的时候，都修改了哪些地方啊？？非常感谢！

**Comment by mumu0419** [comment]
请问有没有用coco预训练mobilenet主干的权重文件呀

**Comment by anmochen** [comment]
抱歉了，这个倒没有，只有mobilenet的image预训练权重




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 中午11:49
收件人:&nbsp;"Byronnar/tensorflow-serving-yolov3"<tensorflow-serving-yolov3@noreply.github.com&gt;;
抄送:&nbsp;"安陌辰"<1210198154@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Byronnar/tensorflow-serving-yolov3] 修改了网络结构，重头开始训练的问题。 (#41)





 
请问有没有用coco预训练mobilenet主干的权重文件呀

**Comment by mumu0419** [comment]
@anmochen 嗷嗷，mobilenet的image预训练权重是用什么数据训练的呀

**Comment by anmochen** [comment]
不好意思，我没说明白，是用的imagenet数据集，你网上搜一下，很多算法模型的预训练权重都是在这个数据集上预训练出来的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:53
收件人:&nbsp;"Byronnar/tensorflow-serving-yolov3"<tensorflow-serving-yolov3@noreply.github.com&gt;;
抄送:&nbsp;"安陌辰"<1210198154@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Byronnar/tensorflow-serving-yolov3] 修改了网络结构，重头开始训练的问题。 (#41)





 
@anmochen 嗷嗷，mobilenet的image预训练权重是用什么数据训练的呀

**Comment by mumu0419** [comment]
@anmochen 好的。因为刚接触，我也不太懂，感谢~
