### ISSUE TITLE
v3-tiny版本问题

### ISSUE THREAD

**Issue by yangzhenjie** [Byronnar/tensorflow-serving-yolov3#42]
1.v3-tiny版本支持是否已经实现？2.yolov3版本 ‘训练了Visdrone2019无人机数据集, 准确率 较高, 训练工业检测数据集（非80类中的一类），mAP为97.51，FPS在1080上测试15-20帧’  就可以到15~20帧么，是服务器上是么？仓主训练好的Visdrone2019无人机数据集的模型能否share我测试看看啊？

**Comment by Byronnar** [comment]
最近在弄其他的, 训练好的模型没了.. 而且感觉还需要改进.

**Comment by yangzhenjie** [comment]
oo 好的，多谢回复
