### ISSUE TITLE
产生先验框出错

### ISSUE THREAD

**Issue by 16534165** [Byronnar/tensorflow-serving-yolov3#43]
Traceback (most recent call last):
  File "anchors_generate.py", line 129, in <module>
    gen_train_txt('./train.txt')
  File "anchors_generate.py", line 118, in gen_train_txt
    objects = parse_xml(xml_path)
  File "anchors_generate.py", line 77, in parse_xml
    name = str(names_dict[name])
KeyError: 'ignored regions'

**Comment by Byronnar** [comment]
'ignored regions' 这个类别跟 'others' 类别去掉. 这两类没什么意义的

**Comment by 16534165** [comment]
在哪儿去掉，没找到啊大佬
还有就是大佬你训练了多久Visdone数据集，精度大概多少，我训练了一晚上精度MAP才30%，是不是我先验框没用这个数据集产生先验框的原因？

**Comment by 16534165** [comment]
@Byronnar

**Comment by Byronnar** [comment]
kmeans的问题 你下一下最新的代码文件, 更新过了.

训练好坏 跟你的 参数配置以及 batch size大小也有关系.

**Comment by Byronnar** [comment]
> @Byronnar

算了, 仓库代码那里不改了, 你自己 手动改一下anchors_generate文件 
        if name != 'others' and name != 'ignored regions':
            bbox = obj.find('bndbox')
            xmin = bbox.find('xmin').text
            ymin = bbox.find('ymin').text
            xmax = bbox.find('xmax').text
            ymax = bbox.find('ymax').text

            name = str(names_dict[name])
            # print(name)
            objects.extend([name, xmin, ymin, xmax, ymax])
其实这个anchors影响没那么大, 就用coco_anchors也可以

**Comment by 16534165** [comment]
谢谢大佬的耐心指导，衷心感谢
