### ISSUE TITLE
服务速度问题

### ISSUE THREAD

**Issue by XiaoPengZong** [Byronnar/tensorflow-serving-yolov3#45]
你好，测试了yolov3_api.py接口，能调通，但有个问题就是速度很慢，跑GPU版本的一张照片都要2~3s，无法达到实时要求，我看其它用tensorflow serving的图片传输用base64格式的，而你提供的接口是图片转化成list传输，想问下时间瓶颈是不是由于这个？是的话应该如何改进，是不是应该修改服务模型的输入类型？对网络定义不太了解，麻烦帮看下

**Comment by XiaoPengZong** [comment]
解决了，修改save_model.py的输入定义部分，然后就可以请求base64的输入，速度提升10倍以上
```python
with tf.name_scope('input'):
    string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data') #string input for the base64 encoded image
    imgs_map = tf.map_fn(
        tf.image.decode_image,
        string_inp,
        dtype=tf.uint8
    ) # decode the jpeg
    imgs_map.set_shape((None, None, None, 3))
    imgs = tf.image.resize_images(imgs_map, [img_size, img_size]) # resize images
    imgs = tf.reshape(imgs, (-1, img_size, img_size, 3)) # reshape them 
    img_float = tf.cast(imgs, dtype=tf.float32) / 255 - 0.5 # and convert them to floats
    # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
    input_data = img_float```

**Comment by Byronnar** [comment]
谢谢你的建议

**Comment by mofang2016** [comment]
> 解决了，修改save_model.py的输入定义部分，然后就可以请求base64的输入，速度提升10倍以上
> 
> ```python
> with tf.name_scope('input'):
>     string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data') #string input for the base64 encoded image
>     imgs_map = tf.map_fn(
>         tf.image.decode_image,
>         string_inp,
>         dtype=tf.uint8
>     ) # decode the jpeg
>     imgs_map.set_shape((None, None, None, 3))
>     imgs = tf.image.resize_images(imgs_map, [img_size, img_size]) # resize images
>     imgs = tf.reshape(imgs, (-1, img_size, img_size, 3)) # reshape them 
>     img_float = tf.cast(imgs, dtype=tf.float32) / 255 - 0.5 # and convert them to floats
>     # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
>     input_data = img_float```
> ```
你好，我也遇到了这个问题，可以看下你修改之后的yolov3_api.py吗？非常感谢

**Comment by XiaoPengZong** [comment]
> > 解决了，修改save_model.py的输入定义部分，然后就可以请求base64的输入，速度提升10倍以上
> > ```python
> > with tf.name_scope('input'):
> >     string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data') #string input for the base64 encoded image
> >     imgs_map = tf.map_fn(
> >         tf.image.decode_image,
> >         string_inp,
> >         dtype=tf.uint8
> >     ) # decode the jpeg
> >     imgs_map.set_shape((None, None, None, 3))
> >     imgs = tf.image.resize_images(imgs_map, [img_size, img_size]) # resize images
> >     imgs = tf.reshape(imgs, (-1, img_size, img_size, 3)) # reshape them 
> >     img_float = tf.cast(imgs, dtype=tf.float32) / 255 - 0.5 # and convert them to floats
> >     # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
> >     input_data = img_float```
> > ```
> 
> 你好，我也遇到了这个问题，可以看下你修改之后的yolov3_api.py吗？非常感谢

只写关键部分
```python
original_image = cv2.imread(input_path + item)

start = time.time()
image_content = base64.b64encode(open(input_path + item,'rb').read()).decode("utf-8")
body = {"signature_name": "predict",
        "instances":  [{"b64": image_content}]}
        
r = requests.post(yolov3_api, headers=headers,data=json.dumps(body)).json()	#post请求

stop = time.time()
print('take time of :', stop - start)
output = np.array(r['predictions'])

output = np.reshape(output, (-1, 10)) 

original_image_size = original_image.shape[:2]
bboxes = utils.postprocess_boxes(output, original_image_size, img_size, 0.3)  # 这一步是将所有可能的预测信息提取出来，主要是三类：类别，可能性，坐标值。
bboxes = utils.nms(bboxes, 0.45, method='nms')  # 这一步是 将刚刚提取出来的信息进行筛选，返回最好的预测值，同样是三类。
image = utils.draw_bbox(original_image, bboxes) # 这一步是把结果画到新图上面。
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
image = Image.fromarray(image)
image.save(output_path + item)  # 保存图片到本地
```

**Comment by netist123** [comment]
> > > 解决了，修改save_model.py的输入定义部分，然后就可以请求base64的输入，速度提升10倍以上
> > > ```python
> > > with tf.name_scope('input'):
> > >     string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data') #string input for the base64 encoded image
> > >     imgs_map = tf.map_fn(
> > >         tf.image.decode_image,
> > >         string_inp,
> > >         dtype=tf.uint8
> > >     ) # decode the jpeg
> > >     imgs_map.set_shape((None, None, None, 3))
> > >     imgs = tf.image.resize_images(imgs_map, [img_size, img_size]) # resize images
> > >     imgs = tf.reshape(imgs, (-1, img_size, img_size, 3)) # reshape them 
> > >     img_float = tf.cast(imgs, dtype=tf.float32) / 255 - 0.5 # and convert them to floats
> > >     # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
> > >     input_data = img_float```
> > > ```
> > 
> > 
> > 你好，我也遇到了这个问题，可以看下你修改之后的yolov3_api.py吗？非常感谢
> 
> 只写关键部分
> 
> ```python
> original_image = cv2.imread(input_path + item)
> 
> start = time.time()
> image_content = base64.b64encode(open(input_path + item,'rb').read()).decode("utf-8")
> body = {"signature_name": "predict",
>         "instances":  [{"b64": image_content}]}
>         
> r = requests.post(yolov3_api, headers=headers,data=json.dumps(body)).json()	#post请求
> 
> stop = time.time()
> print('take time of :', stop - start)
> output = np.array(r['predictions'])
> 
> output = np.reshape(output, (-1, 10)) 
> 
> original_image_size = original_image.shape[:2]
> bboxes = utils.postprocess_boxes(output, original_image_size, img_size, 0.3)  # 这一步是将所有可能的预测信息提取出来，主要是三类：类别，可能性，坐标值。
> bboxes = utils.nms(bboxes, 0.45, method='nms')  # 这一步是 将刚刚提取出来的信息进行筛选，返回最好的预测值，同样是三类。
> image = utils.draw_bbox(original_image, bboxes) # 这一步是把结果画到新图上面。
> image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
> image = Image.fromarray(image)
> image.save(output_path + item)  # 保存图片到本地
> ```



> 解决了，修改save_model.py的输入定义部分，然后就可以请求base64的输入，速度提升10倍以上
> 
> ```python
> with tf.name_scope('input'):
>     string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data') #string input for the base64 encoded image
>     imgs_map = tf.map_fn(
>         tf.image.decode_image,
>         string_inp,
>         dtype=tf.uint8
>     ) # decode the jpeg
>     imgs_map.set_shape((None, None, None, 3))
>     imgs = tf.image.resize_images(imgs_map, [img_size, img_size]) # resize images
>     imgs = tf.reshape(imgs, (-1, img_size, img_size, 3)) # reshape them 
>     img_float = tf.cast(imgs, dtype=tf.float32) / 255 - 0.5 # and convert them to floats
>     # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
>     input_data = img_float```
> ```
感谢使用BASE64的方法，我的模型也提速了60%。（赞！）
  
另外要提醒的是，tf.image.resize_image 大家使用时要注意下。 
主要是它的resize算法和CV的不同，所以会造成些微差别，比如之前测试很好的结果，有可能因为这个些微差别而降低分值。

网上有帖子描述。见： 
https://blog.csdn.net/u011583927/article/details/103307473?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task 

最好还是先把图像用CV处理好在调用API。（建议哈）

**Comment by netist123** [comment]
改成Base64后，发现虽然速度快了，但是图像质量变差了，精确度下降很多, 尤其是小目标。
目前用list传输能很好的保持精确度，不过确实，传输速度比BASE64慢一倍。

**Comment by nobody-cheng** [comment]
`#! /usr/bin/env python
# coding=utf-8


import tensorflow as tf
from core.yolov3 import YOLOV3
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"

savemodel_file_path = "./savemodel/yolov3/1"

ckpt_file = "./checkpoint/yolov3_train_loss=27.0247.ckpt-70"
output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2",
                     "pred_multi_scale/concat"]

img_size = 608
num_channels = 3
with tf.name_scope('input'):
    # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')


    string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data')  # string input for the base64 encoded image
    imgs_map = tf.map_fn(tf.image.decode_image, string_inp, dtype=tf.float32)  # decode the jpeg
    imgs_map.set_shape((None, None, None, 3))
    imgs = tf.image.resize_images(imgs_map, [img_size, img_size])  # resize images
    imgs = tf.reshape(imgs, (-1, img_size, img_size, 3))  # reshape them
    img_float = tf.cast(imgs, dtype=tf.float32) / 255.  # and convert them to floats
    input_data = img_float


model = YOLOV3(input_data, trainable=False)
with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file)


    x_op = sess.graph.get_tensor_by_name('input/input_data:0')
    pred_sbbox_op = sess.graph.get_tensor_by_name('pred_sbbox/concat_2:0')

    pred_mbbox_op = sess.graph.get_tensor_by_name('pred_mbbox/concat_2:0')

    pred_lbbox_op = sess.graph.get_tensor_by_name('pred_lbbox/concat_2:0')

    x_tensor          = tf.saved_model.utils.build_tensor_info(x_op)
    pred_sbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_sbbox_op)
    pred_mbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_mbbox_op)
    pred_lbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_lbbox_op)

    prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={"input":       x_tensor},
        outputs={"pred_sbbox": pred_sbbox_tensor,
                 "pred_mbbox": pred_mbbox_tensor,
                 "pred_lbbox": pred_lbbox_tensor
                 },
        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

    builder = tf.saved_model.builder.SavedModelBuilder(savemodel_file_path)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.tag_constants.SERVING],
                                         signature_def_map={"predict": prediction_signature})

    builder.save()
    print("successful save {}".format(savemodel_file_path))
sess.close()


`

**Comment by nobody-cheng** [comment]
“”“
import tensorflow as tf
from core.yolov3 import YOLOV3
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"

savemodel_file_path = "./savemodel/yolov3/1"

ckpt_file = "./checkpoint/yolov3_train_loss=27.0247.ckpt-70"
output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2",
                     "pred_multi_scale/concat"]

img_size = 608
num_channels = 3
with tf.name_scope('input'):
    # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')


    string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data')  # string input for the base64 encoded image
    imgs_map = tf.map_fn(tf.image.decode_image, string_inp, dtype=tf.float32)  # decode the jpeg
    imgs_map.set_shape((None, None, None, 3))
    imgs = tf.image.resize_images(imgs_map, [img_size, img_size])  # resize images
    imgs = tf.reshape(imgs, (-1, img_size, img_size, 3))  # reshape them
    img_float = tf.cast(imgs, dtype=tf.float32) / 255.  # and convert them to floats
    input_data = img_float


model = YOLOV3(input_data, trainable=False)
with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file)


    x_op = sess.graph.get_tensor_by_name('input/input_data:0')
    pred_sbbox_op = sess.graph.get_tensor_by_name('pred_sbbox/concat_2:0')

    pred_mbbox_op = sess.graph.get_tensor_by_name('pred_mbbox/concat_2:0')

    pred_lbbox_op = sess.graph.get_tensor_by_name('pred_lbbox/concat_2:0')

    x_tensor          = tf.saved_model.utils.build_tensor_info(x_op)
    pred_sbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_sbbox_op)
    pred_mbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_mbbox_op)
    pred_lbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_lbbox_op)

    prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={"input":       x_tensor},
        outputs={"pred_sbbox": pred_sbbox_tensor,
                 "pred_mbbox": pred_mbbox_tensor,
                 "pred_lbbox": pred_lbbox_tensor
                 },
        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

    builder = tf.saved_model.builder.SavedModelBuilder(savemodel_file_path)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.tag_constants.SERVING],
                                         signature_def_map={"predict": prediction_signature})

    builder.save()
    print("successful save {}".format(savemodel_file_path))
sess.close()
”“”

**Comment by nobody-cheng** [comment]
```python
import tensorflow as tf
from core.yolov3 import YOLOV3
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"

savemodel_file_path = "./savemodel/yolov3/1"

ckpt_file = "./checkpoint/yolov3_train_loss=27.0247.ckpt-70"
output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2",
                     "pred_multi_scale/concat"]

img_size = 608
num_channels = 3
with tf.name_scope('input'):
    # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')


    string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data')  # string input for the base64 encoded image
    imgs_map = tf.map_fn(tf.image.decode_image, string_inp, dtype=tf.float32)  # decode the jpeg
    imgs_map.set_shape((None, None, None, 3))
    imgs = tf.image.resize_images(imgs_map, [img_size, img_size])  # resize images
    imgs = tf.reshape(imgs, (-1, img_size, img_size, 3))  # reshape them
    img_float = tf.cast(imgs, dtype=tf.float32) / 255.  # and convert them to floats
    input_data = img_float


model = YOLOV3(input_data, trainable=False)
with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file)


    x_op = sess.graph.get_tensor_by_name('input/input_data:0')
    pred_sbbox_op = sess.graph.get_tensor_by_name('pred_sbbox/concat_2:0')

    pred_mbbox_op = sess.graph.get_tensor_by_name('pred_mbbox/concat_2:0')

    pred_lbbox_op = sess.graph.get_tensor_by_name('pred_lbbox/concat_2:0')

    x_tensor          = tf.saved_model.utils.build_tensor_info(x_op)
    pred_sbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_sbbox_op)
    pred_mbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_mbbox_op)
    pred_lbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_lbbox_op)

    prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={"input":       x_tensor},
        outputs={"pred_sbbox": pred_sbbox_tensor,
                 "pred_mbbox": pred_mbbox_tensor,
                 "pred_lbbox": pred_lbbox_tensor
                 },
        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

    builder = tf.saved_model.builder.SavedModelBuilder(savemodel_file_path)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.tag_constants.SERVING],
                                         signature_def_map={"predict": prediction_signature})

    builder.save()
    print("successful save {}".format(savemodel_file_path))
sess.close()
```

```python
def object_detect(input_path="./road.jpg", output_path='./demo.jpg'):
    img_size = 608
    num_channels = 3
    image_path = input_path 
    original_image = cv2.imread(image_path)


    frame_size = original_image.shape[:2]
    image_content = base64.b64encode(open(input_path,'rb').read()).decode("utf-8")
    


    yolov3_api = "http://localhost:8501/v1/models/yolov3:predict"   # 刚刚产生的接口
    headers = {"Content-type": "application/json"}

    body = {"signature_name": "predict", "instances":  [{"b64": image_content}]}
    r = requests.post(yolov3_api, headers=headers, data=json.dumps(body)).json() 	#post请求

    output = np.array(r['predictions'])

    pred_sbbox = np.array(output[0]["pred_sbbox"])
    pred_mbbox = np.array(output[0]["pred_mbbox"])
    pred_lbbox = np.array(output[0]["pred_lbbox"])

    pred_bbox = np.concatenate([np.reshape(pred_sbbox, (-1, 5 + num_classes)),
                                np.reshape(pred_mbbox, (-1, 5 + num_classes)),
                                np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0)

    bboxes = utils.postprocess_boxes(pred_bbox, frame_size, img_size, 0.4)
    bboxes = utils.nms(bboxes, 0.45, method='nms')
    image = utils.draw_bbox(original_image, bboxes, classes=num_classes)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image = Image.fromarray(image)
```
你好，我的base64解码saveModel如上，当我按照原版的传输二进制数据的时候检测效果良好，但是使用base64编码后就一个都难以检出

**Comment by oaifaye** [comment]
> 模型转换pb如下
> 
> ```python
> import tensorflow as tf
> from core.yolov3 import YOLOV3
> import os
> 
> os.environ["CUDA_VISIBLE_DEVICES"] = "1"
> 
> savemodel_file_path = "./savemodel/yolov3/1"
> 
> ckpt_file = "./checkpoint/yolov3_train_loss=27.0247.ckpt-70"
> output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2",
>                      "pred_multi_scale/concat"]
> 
> img_size = 608
> num_channels = 3
> with tf.name_scope('input'):
>     # input_data = tf.placeholder(dtype=tf.float32, shape=[None, img_size, img_size, num_channels], name='input_data')
> 
> 
>     string_inp = tf.placeholder(tf.string, shape=(None,), name='input_data')  # string input for the base64 encoded image
>     imgs_map = tf.map_fn(tf.image.decode_image, string_inp, dtype=tf.float32)  # decode the jpeg
>     imgs_map.set_shape((None, None, None, 3))
>     imgs = tf.image.resize_images(imgs_map, [img_size, img_size])  # resize images
>     imgs = tf.reshape(imgs, (-1, img_size, img_size, 3))  # reshape them
>     img_float = tf.cast(imgs, dtype=tf.float32) / 255.  # and convert them to floats
>     input_data = img_float
> 
> 
> model = YOLOV3(input_data, trainable=False)
> with tf.Session() as sess:
>     saver = tf.train.Saver()
>     saver.restore(sess, ckpt_file)
> 
> 
>     x_op = sess.graph.get_tensor_by_name('input/input_data:0')
>     pred_sbbox_op = sess.graph.get_tensor_by_name('pred_sbbox/concat_2:0')
> 
>     pred_mbbox_op = sess.graph.get_tensor_by_name('pred_mbbox/concat_2:0')
> 
>     pred_lbbox_op = sess.graph.get_tensor_by_name('pred_lbbox/concat_2:0')
> 
>     x_tensor          = tf.saved_model.utils.build_tensor_info(x_op)
>     pred_sbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_sbbox_op)
>     pred_mbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_mbbox_op)
>     pred_lbbox_tensor = tf.saved_model.utils.build_tensor_info(pred_lbbox_op)
> 
>     prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
>         inputs={"input":       x_tensor},
>         outputs={"pred_sbbox": pred_sbbox_tensor,
>                  "pred_mbbox": pred_mbbox_tensor,
>                  "pred_lbbox": pred_lbbox_tensor
>                  },
>         method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)
> 
>     builder = tf.saved_model.builder.SavedModelBuilder(savemodel_file_path)
>     builder.add_meta_graph_and_variables(sess,
>                                          [tf.saved_model.tag_constants.SERVING],
>                                          signature_def_map={"predict": prediction_signature})
> 
>     builder.save()
>     print("successful save {}".format(savemodel_file_path))
> sess.close()
> ```
> 
> post请求如下
> 
> ```python
> def object_detect(input_path="./road.jpg", output_path='./demo.jpg'):
>     img_size = 608
>     num_channels = 3
>     image_path = input_path 
>     original_image = cv2.imread(image_path)
> 
> 
>     frame_size = original_image.shape[:2]
>     image_content = base64.b64encode(open(input_path,'rb').read()).decode("utf-8")
>     
> 
> 
>     yolov3_api = "http://localhost:8501/v1/models/yolov3:predict"   # 刚刚产生的接口
>     headers = {"Content-type": "application/json"}
> 
>     body = {"signature_name": "predict", "instances":  [{"b64": image_content}]}
>     r = requests.post(yolov3_api, headers=headers, data=json.dumps(body)).json() 	#post请求
> 
>     output = np.array(r['predictions'])
> 
>     pred_sbbox = np.array(output[0]["pred_sbbox"])
>     pred_mbbox = np.array(output[0]["pred_mbbox"])
>     pred_lbbox = np.array(output[0]["pred_lbbox"])
> 
>     pred_bbox = np.concatenate([np.reshape(pred_sbbox, (-1, 5 + num_classes)),
>                                 np.reshape(pred_mbbox, (-1, 5 + num_classes)),
>                                 np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0)
> 
>     bboxes = utils.postprocess_boxes(pred_bbox, frame_size, img_size, 0.4)
>     bboxes = utils.nms(bboxes, 0.45, method='nms')
>     image = utils.draw_bbox(original_image, bboxes, classes=num_classes)
>     image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
>     image = Image.fromarray(image)
> ```
> 
> 你好，我的base64解码saveModel如上，当我按照原版的传输二进制数据的时候检测效果良好，但是使用base64编码后就一个都难以检出

base64之前不能简单reshape，需要保留比例reshape，然后补128，可以仿照 core.util.image_preporcess 这个方法，去掉image_paded = image_paded / 255.这一行，然后先调用这个方法，再掉api，精度就恢复了

def image_preporcess(image, target_size, gt_boxes=None):

ih, iw    = target_size
h,  w, _  = image.shape

scale = min(iw/w, ih/h)
nw, nh  = int(scale * w), int(scale * h)
image_resized = cv2.resize(image, (nw, nh))

image_paded = np.full(shape=[ih, iw, 3], fill_value=128.0)
dw, dh = (iw - nw) // 2, (ih-nh) // 2
image_paded[dh:nh+dh, dw:nw+dw, :] = image_resized
# image_paded = image_paded / 255.

if gt_boxes is None:
    return image_paded

else:
    gt_boxes[:, [0, 2]] = gt_boxes[:, [0, 2]] * scale + dw
    gt_boxes[:, [1, 3]] = gt_boxes[:, [1, 3]] * scale + dh
    return image_paded, gt_boxes
