### ISSUE TITLE
bounding box的获取

### ISSUE THREAD

**Issue by MC1016** [Byronnar/tensorflow-serving-yolov3#47]
博主您好，看了您的代码有一点不太明白，在image_demo的程序里对图片的推理过程，是如何获得其bounding box的，程序里是直接从PB文件里获得pred_sbbox lbbox  mbbox的嘛？，这三个尺度的特征图是怎么得到的？ 我打印op节点后续对mbbox lbbox sbbox的操作没太看懂。也就是推理阶段yolo输出三个尺度的特征图后的处理

**Comment by Byronnar** [comment]
这里有什么不理解的么, utils.read_pb_return_tensors拿到tensor, np.concatenate 组合一下
