### ISSUE TITLE
预测结果错误

### ISSUE THREAD

**Issue by 18483666678** [Byronnar/tensorflow-serving-yolov3#49]
使用image_demo.py测试的结果是错误的，但是使用image_demo_multi.py检测结果是正确的。经过检查对比，发现这行代码的问题：`        original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)
`，在YunYang1994中的代码没有错误，我不知道这是为什么，转换了颜色通道后出现错误的原因？希望解答，感谢！

**Comment by Byronnar** [comment]
给出具体报错信息， 我这边运行没问题啊，这个代码只是转换颜色通道

**Comment by 18483666678** [comment]
使用image_demo.py预测的时候，使用了颜色转换通道代码， `original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)`得到的坐标框信息和标签是错误的。不使用颜色转换通道代码检测得到的坐标信息和标签是正确的。使用颜色转换代码得到bboxs的信息：`bboxes: [array([ 97.08699799,  18.46921921, 184.62911987, 102.36797333, 0.48056901,   0.        ]), 
         array([605.9598999 ,  40.90876389, 640.84716797,  88.03312683, 0.87972343,   1.        ]), 
         array([629.0645752 ,  38.09148788, 671.53491211,  91.077034  , 0.84932989,   1.        ]), 
         array([488.91482544,  60.84961319, 531.20568848, 103.77033997, 0.7517032 ,   1.        ]), 
         array([7.50905029e+02, 2.00015316e+01, 7.99000000e+02, 8.51884079e+01, 7.19611287e-01, 1.00000000e+00]), 
         array([7.10551392e+02, 2.16745472e+01, 7.54037781e+02, 6.12573814e+01, 5.99805892e-01, 1.00000000e+00])]
`。不使用颜色转换代码得到bboxs的信息：`bboxes: [array([333.68093872,  92.72576141, 395.18414307, 260.40097046, 0.97952676,   3.        ]),
         array([472.69433594,  90.42610168, 551.36669922, 262.91897583, 0.97933066,   3.        ]), 
         array([281.04785156,  96.17131805, 343.27261353, 257.42095947, 0.97919559,   3.        ]), 
         array([192.42025757,  94.18016815, 277.33627319, 322.35464478, 0.96363199,   3.        ]), 
         array([636.60119629, 150.24543762, 799.        , 518.30529785, 0.90065336,   3.        ]), 
         array([  9.46444511,  84.42411804, 252.58602905, 522.17132568, 0.89593786,   3.        ]), 
         array([243.24169922,  86.17984772, 289.98095703, 268.70315552, 0.46351069,   3.        ])]`。目前还没有找到原因。

**Comment by Byronnar** [comment]
YunYang1994中用了两次转换， 你在utils.py中加上这个
 image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
即
def image_preporcess(image, target_size, gt_boxes=None):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)

    ih, iw    = target_size
    h,  w, _  = image.shape
然后删掉original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)

**Comment by 18483666678** [comment]
感谢，但是在我的代码测试里面，增加
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)后，删除掉 
original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)检测到的结果依然是错误的，在保留后结果又是正确的。我不明白的是，再YunYang1994中颜色通道变换跟检测的结果没有关系，而在这个代码里面会出现检测结果不同。是因为您修改了网络结构导致的还是我的数据集的问题？

**Comment by Byronnar** [comment]
我真没碰到你这种问题，网络结构不会被你这个影响的
