### ISSUE TITLE
大佬，啥时候更新呀！期待！

### ISSUE THREAD

**Issue by dodogoffy** [Byronnar/tensorflow-serving-yolov3#50]

**Comment by Byronnar** [comment]
更新哪一个，最近在打比赛，可能没时间艾

**Comment by dodogoffy** [comment]
> 新哪一个，最近在打比赛，可能没时间艾

tensorflow lite！

**Comment by Byronnar** [comment]
你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。

**Comment by dodogoffy** [comment]
> 你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。

liangoffy 谢谢啊！！

**Comment by dodogoffy** [comment]
> 你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。
微信 liangoffy 谢谢啊！！
我之前漏看了信息，现在才看到。

**Comment by dodogoffy** [comment]
> 你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。

微信 liangoffy 谢谢啊！！
我之前漏看了信息，现在才看到。

**Comment by dodogoffy** [comment]
> 你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。
大佬快加我微信 ，谢谢啊

**Comment by wangjiachenchen** [comment]
不能直接用tflite_convert 对模型进行量化吧？
<tf.Tensor 'input/input_data:0' shape=<unknown> dtype=float32>
input的shape是可变的，如果我写一个正在使用的大小，会出现如下错误：
Check failed: start_indices_size <= num_input_axes (2 vs. 1)StridedSlice op requires no more than 1 start indices

**Comment by ai1361720220000** [comment]
> 你微信多少，我加一下你吧，tensorflow lite 还没完成， 做了一点，发给你。

大佬，tflite完成了吗？我转化tflite可以，但是量化之后就会出问题。

**Comment by ai1361720220000** [comment]
> 不能直接用tflite_convert 对模型进行量化吧？
> <tf.Tensor 'input/input_data:0' shape= dtype=float32>
> input的shape是可变的，如果我写一个正在使用的大小，会出现如下错误：
> Check failed: start_indices_size <= num_input_axes (2 vs. 1)StridedSlice op requires no more than 1 start indices

可以参考https://github.com/YunYang1994/tensorflow-yolov3/issues/232，因为yolov3.py里的decode()使用了tf.newaxis，改成tf.expand_dims就好了。
