### ISSUE TITLE
您好，想向你请教，decode_mobile为什么没有用到anchor？

### ISSUE THREAD

**Issue by dodogoffy** [Byronnar/tensorflow-serving-yolov3#52]
https://github.com/Byronnar/tensorflow-serving-yolov3/blob/f6e1d967f7004f830e8fb0541afa3731de6bda51/core/yolov3.py#L106

https://github.com/Byronnar/tensorflow-serving-yolov3/blob/f6e1d967f7004f830e8fb0541afa3731de6bda51/core/yolov3_mobilenetv2.py#L140

**Comment by Byronnar** [comment]
你好， 可以先去网上看一下 mobilenetv2的代码

**Comment by dodogoffy** [comment]
> 你好， 可以先去网上看一下 mobilenetv2的代码

好的 谢谢

**Comment by dodogoffy** [comment]
> 你好， 可以先去网上看一下 mobilenetv2的代码

您好，我按照你的代码在我的代码添加了mobilenet v2，可以训练。
![image](https://user-images.githubusercontent.com/46831826/72324207-57ff9600-36e5-11ea-89d7-b2f088797e29.png)
训练好模型之后，打算evaluate，把evaluate.py的建图的改成 from yolov3_mobilenetv2 import YOLOV3,
但是计算出来的mAP为0.0x，想问问你，我的操作有什么问题？
希望您给我一些建议。谢谢！

![image](https://user-images.githubusercontent.com/46831826/72324395-ca707600-36e5-11ea-8d13-9a05515e2536.png)
loss的下降还是比较正常的。

**Comment by dodogoffy** [comment]
> 你好， 可以先去网上看一下 mobilenetv2的代码

您好，我根据你的建议阅读了一下mobilenetv2的代码。
我有一个问题：
原始的decode：输出的格式是 xywh，采用的是YOLOv3的边框预测公式.

decode_mobile: 输出的格式是x1y1x2y2.

这两者之间有什么区别和联系吗？

**Comment by walkeryu123** [comment]
> > 你好， 可以先去网上看一下 mobilenetv2的代码
> 
> 您好，我按照你的代码在我的代码添加了mobilenet v2，可以训练。
> ![image](https://user-images.githubusercontent.com/46831826/72324207-57ff9600-36e5-11ea-89d7-b2f088797e29.png)
> 训练好模型之后，打算evaluate，把evaluate.py的建图的改成 from yolov3_mobilenetv2 import YOLOV3,
> 但是计算出来的mAP为0.0x，想问问你，我的操作有什么问题？
> 希望您给我一些建议。谢谢！
> 
> ![image](https://user-images.githubusercontent.com/46831826/72324395-ca707600-36e5-11ea-8d13-9a05515e2536.png)
> loss的下降还是比较正常的。



> > 你好， 可以先去网上看一下 mobilenetv2的代码
> 
> 您好，我按照你的代码在我的代码添加了mobilenet v2，可以训练。
> ![image](https://user-images.githubusercontent.com/46831826/72324207-57ff9600-36e5-11ea-89d7-b2f088797e29.png)
> 训练好模型之后，打算evaluate，把evaluate.py的建图的改成 from yolov3_mobilenetv2 import YOLOV3,
> 但是计算出来的mAP为0.0x，想问问你，我的操作有什么问题？
> 希望您给我一些建议。谢谢！
> 
> ![image](https://user-images.githubusercontent.com/46831826/72324395-ca707600-36e5-11ea-8d13-9a05515e2536.png)
> loss的下降还是比较正常的。

你好，

我也遇到一样问题了，训练时候看起来一切正常，evaluate时候mAP基本是0，请问你是怎么解决的？

**Comment by dodogoffy** [comment]
> > > 你好， 可以先去网上看一下 mobilenetv2的代码
> > 
> > 
> > 您好，我按照你的代码在我的代码添加了mobilenet v2，可以训练。
> > ![image](https://user-images.githubusercontent.com/46831826/72324207-57ff9600-36e5-11ea-89d7-b2f088797e29.png)
> > 训练好模型之后，打算evaluate，把evaluate.py的建图的改成 from yolov3_mobilenetv2 import YOLOV3,
> > 但是计算出来的mAP为0.0x，想问问你，我的操作有什么问题？
> > 希望您给我一些建议。谢谢！
> > ![image](https://user-images.githubusercontent.com/46831826/72324395-ca707600-36e5-11ea-8d13-9a05515e2536.png)
> > loss的下降还是比较正常的。
> 
> > > 你好， 可以先去网上看一下 mobilenetv2的代码
> > 
> > 
> > 您好，我按照你的代码在我的代码添加了mobilenet v2，可以训练。
> > ![image](https://user-images.githubusercontent.com/46831826/72324207-57ff9600-36e5-11ea-89d7-b2f088797e29.png)
> > 训练好模型之后，打算evaluate，把evaluate.py的建图的改成 from yolov3_mobilenetv2 import YOLOV3,
> > 但是计算出来的mAP为0.0x，想问问你，我的操作有什么问题？
> > 希望您给我一些建议。谢谢！
> > ![image](https://user-images.githubusercontent.com/46831826/72324395-ca707600-36e5-11ea-8d13-9a05515e2536.png)
> > loss的下降还是比较正常的。
> 
> 你好，
> 
> 我也遇到一样问题了，训练时候看起来一切正常，evaluate时候mAP基本是0，请问你是怎么解决的？

检查一下evaluate的输出格式（是xywh还是x1y1x2y2）。
打label的时候要相对应。
原始的decode：输出的格式是 xywh，采用的是YOLOv3的边框预测公式.
decode_mobile: 输出的格式是x1y1x2y2。

**Comment by walkeryu123** [comment]
谢谢，我试着把evaluate部分的xywh改成x1y1x2y2,程序一直不对，我试着把decode_mobile输出改成xywh后看起来好像挺正常的

**Comment by netist123** [comment]
> 谢谢，我试着把evaluate部分的xywh改成x1y1x2y2,程序一直不对，我试着把decode_mobile输出改成xywh后看起来好像挺正常的

您是怎么改的，能分享一下这几行代码吗？

**Comment by walkeryu123** [comment]
> > 谢谢，我试着把evaluate部分的xywh改成x1y1x2y2,程序一直不对，我试着把decode_mobile输出改成xywh后看起来好像挺正常的
> 
> 您是怎么改的，能分享一下这几行代码吗？

你邮箱多少，我把文件发给你吧，我后来没用这个，我也不确定对不对，你自己再看看

**Comment by netist123** [comment]
> > > 谢谢，我试着把evaluate部分的xywh改成x1y1x2y2,程序一直不对，我试着把decode_mobile输出改成xywh后看起来好像挺正常的
> > 
> > 
> > 您是怎么改的，能分享一下这几行代码吗？
> 
> 你邮箱多少，我把文件发给你吧，我后来没用这个，我也不确定对不对，你自己再看看

好的谢谢!! 邮箱是netist@163.com.
