### ISSUE TITLE
建立无法yolov3的网络

### ISSUE THREAD

**Issue by anmochen** [Byronnar/tensorflow-serving-yolov3#53]
NotImplementedError: Can not build up yolov3 network!
这是运行train.py文件的时候，出现上述问题，麻烦看一下，谢谢！

**Comment by Byronnar** [comment]
我刚刚下载下来跑了一遍，除了仓库的数据太少，其他没什么问题， 你可能是修改了哪些地方。建议重新 下载我的代码测试，做了一些调整

**Comment by anmochen** [comment]
已经下载了，正在测，

**Comment by anmochen** [comment]
真的非常感谢您的回复，在麻烦您两个问题，首先是部署的时候，tmp文件夹是在主文件夹下新建的么？（感觉非常弱质。。。），还有就是，如果需要生成自己数据集对应的权重文件的话，都需要改哪些地方啊，除了names, class, anchors这些，还有其他的么？非常感谢！！
