### ISSUE TITLE
提高小目标检测精度的办法

### ISSUE THREAD

**Issue by HaiLongEmb** [Byronnar/tensorflow-serving-yolov3#54]
您好，
       感谢你的模型，效果很好，但我目前遇到一个问题，我在训练私有数据集时（1920*1080分辨率），发现小目标检测的精度不高，我使用迁移训练的方式，加载预训练模型进行训练，并且使用k-means，获取到新的anchor。效果不理想，请问有什么好办法提高小目标的准确率，降低误报率吗？

**Comment by Byronnar** [comment]
小目标检测， 可以尝试：
1 加入注意力机制
2 图片裁剪， 保留 标注框集中的地方， 把无用的背景去掉。
3 使用 随机裁剪，将图片 分成小的多张，再训练

**Comment by HaiLongEmb** [comment]
@Byronnar 感谢分享经验，2、3属于数据曾广，用TensorFlow自带的曾广API好还是需要自己实现呢，另外注意力机制，有参考例子吗？

**Comment by Byronnar** [comment]
都可以啊， 网上找一下
