### ISSUE TITLE
部署tensorflow serving之后，测试服务，发现没调用GPU

### ISSUE THREAD

**Issue by mofang2016** [Byronnar/tensorflow-serving-yolov3#55]
测试yolov3_api.py接口，速度很慢，原因是服务只调用CPU，没调用GPU，如何让服务调用GPU呢

**Comment by Byronnar** [comment]
这是 服务器上调用，cpu足够了，响应时间很短，参考这个 https://github.com/Byronnar/tensorflow-serving-yolov3/issues/45
时间1秒多就可以了，再要更快可以做模型压缩或者换backbone
