### ISSUE TITLE
请问大佬无人机的原始图片是多大？缩放到608以后效果怎么样？

### ISSUE THREAD

**Issue by yanchangqin** [Byronnar/tensorflow-serving-yolov3#6]
如题，我这边项目原始图片为1920x1080的大图，最大的有4k，不清楚是不是缩放过度的原因，检测出来的目标置信度比较低，基本在0.2~0.3左右，我也是缩到了608！

**Comment by Byronnar** [comment]
我用的是 多尺度训练，你显存大的话，建议[608,832]多尺度训练，然后classes.names里面10类，其他地方细节再调试一下会好些
