### ISSUE TITLE
关于convert_weight.py的问题

### ISSUE THREAD

**Issue by kalayan** [Byronnar/tensorflow-serving-yolov3#60]
大神您好！非常感谢您这么好的代码！

小白想问一下您convert_weight.py是做什么的呢？

我现在用coco的预训练模型训练VOC训练集，然后会得到ckpt（三个文件），但是再用这个ckpt训练自己的训练集的时候，通过‘__C.TRAIN.INITIAL_WEIGHT = 自己训练后的ckpt’，就会报warning：ckpt does not exist !!! 就又从头开始训练了，感觉是要再convert_weight.py一下，但是convert_weight.py就报错了。

请问一下这时候要怎么办呢？谢谢！我是想用coco的预训练模型训练VOC训练集，得到模型再训练别的训练集。

**Comment by kindasweetgal** [comment]
不好意思能问你个问题么，我是用convert_weight.py想从这个基础上进行训练，但是为什么训练的时候报backbone加载不了预训练模型呢，然后他就从头训练了。。

**Comment by Byronnar** [comment]
这个问题应该解决了吧,准备关闭了
