### ISSUE TITLE
config.py文件的__C.TRAIN.INPUT_SIZE问题请教

### ISSUE THREAD

**Issue by kalayan** [Byronnar/tensorflow-serving-yolov3#61]
您好，请问一下__C.TRAIN.INPUT_SIZE = [320, 352, 384, 416, 448, 480, 512, 544, 576, 608] 为什么这么设置呢？

我好像明白INPUT_SIZE 是要要32的倍数，那如果我的训练集图像是(1080, 1920, 3)的，INPUT_SIZE 需要设置成什么呢？

非常感谢！

**Comment by Byronnar** [comment]
如果你显存够大的话可以尽量设置大一些，使用32的倍数，比如832这种。

**Comment by kalayan** [comment]
> 如果你显存够大的话可以尽量设置大一些，使用32的倍数，比如832这种。

谢谢！
