### ISSUE TITLE
关于固化moblienetv2 ckpt成pb模型文件的问题

### ISSUE THREAD

**Issue by alwan1989** [Byronnar/tensorflow-serving-yolov3#63]
楼主大大,请问下固化会有bug啊,归一化层那里会有问题,怎么解决呢?用你的freeze_graph.py脚本不行,我已经把from core.yolov3_mobilenetv2 import YOLOV3这句改好了,可以告诉我吗?谢谢了^

**Comment by Byronnar** [comment]
不好意思啊，固化的话，你不能直接用freeze那个脚本的，需要修改一下， 因为darknet跟mobilenet是不一样的， 具体怎么修改，我最近没时间更新艾，你可以先研究一下。

**Comment by dodogoffy** [comment]
> 楼主大大,请问下固化会有bug啊,归一化层那里会有问题,怎么解决呢?用你的freeze_graph.py脚本不行,我已经把from core.yolov3_mobilenetv2 import YOLOV3这句改好了,可以告诉我吗?谢谢了^

同遇到相同的问题（哭）

**Comment by dodogoffy** [comment]
> 不好意思啊，固化的话，你不能直接用freeze那个脚本的，需要修改一下， 因为darknet跟mobilenet是不一样的， 具体怎么修改，我最近没时间更新艾，你可以先研究一下。

是需要知道mobilenet的输出节点名称吗？但是我找不到mobilenet的输出节点名称是哪个。

**Comment by netist123** [comment]
我也碰到这个问题。freeze_graph无法固化，save_model也无法用。

**Comment by poemlin** [comment]
mark一下，改了一下能freeze了，inference还是出错。 @Byronnar 大佬帮忙康康

**Comment by Byronnar** [comment]
报什么错?  freeze代码对么,  注意尺度和 权重转换. 可以把代码跟错误贴上来

**Comment by dodogoffy** [comment]
我现在也是能freeze了，inference的时候单张图片测试是有结果的，但是测试视频的时候就没有输出。

**Comment by dodogoffy** [comment]
> mark一下，改了一下能freeze了，inference还是出错。 @Byronnar 大佬帮忙康康

你试下把freeze出来的.pb文件测试一下单张图片看看有没有结果？

**Comment by alwan1989** [comment]
> 我现在也是能freeze了，推断的时候单张图片测试是有结果的，但是测试视频的时候就没有输出。

可以把能的固化脚本分享下吗？

**Comment by dodogoffy** [comment]
> > 我现在也是能freeze了，推断的时候单张图片测试是有结果的，但是测试视频的时候就没有输出。
> 
> 可以把能的固化脚本分享下吗？
我之前是遇到这个错误tf.import_graph_def（）错误
然后照着下面的issues加了几行代码
https://github.com/onnx/tensorflow-onnx/issues/77

**Comment by nobody-cheng** [comment]
我是修改了这两行可以转为pb文件，但是inference的时候报了一个类型错误
![Snipaste_2020-04-27_10-18-48](https://user-images.githubusercontent.com/34908468/80328018-9e31cd00-8870-11ea-98fe-013d65f8571b.jpg)
错误如下：
![Snipaste_2020-04-27_10-20-25](https://user-images.githubusercontent.com/34908468/80328054-be618c00-8870-11ea-8d97-8b20e12a6861.jpg)
cuda10， cudnn7，python3.7， tf1.14.0 
不知是否报一样的错误，是否已经解决问题？？

**Comment by ai1361720220000** [comment]
> 我是修改了这两行可以转为pb文件，但是inference的时候报了一个类型错误
> ![Snipaste_2020-04-27_10-18-48](https://user-images.githubusercontent.com/34908468/80328018-9e31cd00-8870-11ea-98fe-013d65f8571b.jpg)
> 错误如下：
> ![Snipaste_2020-04-27_10-20-25](https://user-images.githubusercontent.com/34908468/80328054-be618c00-8870-11ea-8d97-8b20e12a6861.jpg)
> cuda10， cudnn7，python3.7， tf1.14.0
> 不知是否报一样的错误，是否已经解决问题？？
> 
> # fix nodes
> `def read_pb_return_tensors(graph, pb_file, return_elements):
> 
> ```
> with tf.gfile.FastGFile(pb_file, 'rb') as f:
>     frozen_graph_def = tf.GraphDef()
>     frozen_graph_def.ParseFromString(f.read())
> 
> with graph.as_default():
>     # fix nodes
>     for node in frozen_graph_def.node:
>         if node.op == 'RefSwitch':
>             node.op = 'Switch'
>             for index in range(len(node.input)):
>                 if 'moving_' in node.input[index]:
>                     node.input[index] = node.input[index] + '/read'
>         elif node.op == 'AssignSub':
>             node.op = 'Sub'
>             if 'use_locking' in node.attr: del node.attr['use_locking']
>         elif node.op == 'AssignAdd':
>             node.op = 'Add'
>             if 'use_locking' in node.attr: del node.attr['use_locking']
>         elif node.op == 'Assign':
>             node.op = 'Identity'
>             if 'use_locking' in node.attr: del node.attr['use_locking']
>             if 'validate_shape' in node.attr: del node.attr['validate_shape']
>             if len(node.input) == 2:
>                 node.input[0] = node.input[1]
>                 del node.input[1]
>                 
>     return_elements = tf.import_graph_def(frozen_graph_def, return_elements=return_elements)
> return return_elements`
> ```

报同样的错误，不知道是否解决？

**Comment by nobody-cheng** [comment]
> > 我是修改了这两行可以转为pb文件，但是inference的时候报了一个类型错误
> > ![Snipaste_2020-04-27_10-18-48](https://user-images.githubusercontent.com/34908468/80328018-9e31cd00-8870-11ea-98fe-013d65f8571b.jpg)
> > 错误如下：
> > ![Snipaste_2020-04-27_10-20-25](https://user-images.githubusercontent.com/34908468/80328054-be618c00-8870-11ea-8d97-8b20e12a6861.jpg)
> > cuda10， cudnn7，python3.7， tf1.14.0
> > 不知是否报一样的错误，是否已经解决问题？？
> > # fix nodes
> > `def read_pb_return_tensors(graph, pb_file, return_elements):
> > ```
> > with tf.gfile.FastGFile(pb_file, 'rb') as f:
> >     frozen_graph_def = tf.GraphDef()
> >     frozen_graph_def.ParseFromString(f.read())
> > 
> > with graph.as_default():
> >     # fix nodes
> >     for node in frozen_graph_def.node:
> >         if node.op == 'RefSwitch':
> >             node.op = 'Switch'
> >             for index in range(len(node.input)):
> >                 if 'moving_' in node.input[index]:
> >                     node.input[index] = node.input[index] + '/read'
> >         elif node.op == 'AssignSub':
> >             node.op = 'Sub'
> >             if 'use_locking' in node.attr: del node.attr['use_locking']
> >         elif node.op == 'AssignAdd':
> >             node.op = 'Add'
> >             if 'use_locking' in node.attr: del node.attr['use_locking']
> >         elif node.op == 'Assign':
> >             node.op = 'Identity'
> >             if 'use_locking' in node.attr: del node.attr['use_locking']
> >             if 'validate_shape' in node.attr: del node.attr['validate_shape']
> >             if len(node.input) == 2:
> >                 node.input[0] = node.input[1]
> >                 del node.input[1]
> >                 
> >     return_elements = tf.import_graph_def(frozen_graph_def, return_elements=return_elements)
> > return return_elements`
> > ```
> 
> 报同样的错误，不知道是否解决？
freeze_graph.py
```
import tensorflow as tf
from core.yolov3_separable_channel import YOLOV3
import os

output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2"]


def freeze_graph3(ckpt_file, output_pb_file):
    with tf.name_scope('input'):
        input_data = tf.placeholder(dtype=tf.float32, name='input_data')
        # input_data = tf.placeholder(dtype=tf.float32, shape=[None, None, None, 3], name='input_data')

    model = YOLOV3(input_data, trainable=tf.constant(False, dtype=tf.bool))
    print(model.conv_sbbox, model.conv_mbbox, model.conv_lbbox)

    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file)
    saver = tf.train.import_meta_graph(ckpt_file + '.meta', clear_devices=True)


    converted_graph_def = tf.graph_util.convert_variables_to_constants(sess,
                                                                       input_graph_def=sess.graph.as_graph_def(),
                                                                       output_node_names=output_node_names)

    with tf.gfile.GFile(output_pb_file, "wb") as f:
        f.write(converted_graph_def.SerializeToString())
    print('==========  successful  ===========')

if __name__ == '__main__':
    os.environ["CUDA_VISIBLE_DEVICES"] = '5'
    ckpt_file = "./checkpoint_head-separable-resize-half-channel_backbone-half-channel-residual-block/best_model_Epoch_38_step_121296_mAP_0.7851_lr_4.5932e-05_loss_56.5200"
    output_pb_file = "./yolov3_debugggggggg.pb"
    freeze_graph3(ckpt_file, output_pb_file)
```
加载PB模型
```
    def read_pb_return_tensors(self):
        with tf.gfile.FastGFile(self.pb_file, 'rb') as f:
            frozen_graph_def = tf.GraphDef()
            frozen_graph_def.ParseFromString(f.read())

        with self.graph.as_default():
            # fix nodes
            for node in frozen_graph_def.node:
                if node.op == 'RefSwitch':
                    node.op = 'Switch'
                    for index in range(len(node.input)):
                        if 'moving_' in node.input[index]:
                            node.input[index] = node.input[index] + '/read'
                elif node.op == 'AssignSub':
                    node.op = 'Sub'
                    if 'use_locking' in node.attr:
                        del node.attr['use_locking']
                elif node.op == 'AssignAdd':
                    node.op = 'Add'
                    if 'use_locking' in node.attr:
                        del node.attr['use_locking']
                elif node.op == 'Assign':
                    node.op = 'Identity'
                    if 'use_locking' in node.attr:
                        del node.attr['use_locking']
                    if 'validate_shape' in node.attr:
                        del node.attr['validate_shape']
                    if len(node.input) == 2:
                        node.input[0] = node.input[1]
                        del node.input[1]

            return_elements = tf.import_graph_def(frozen_graph_def, return_elements=self.return_elements)
        return return_elements
```
我是这么解决的
