### ISSUE TITLE
有关输入尺寸__C.TRAIN.INPUT_SIZE 的设置问题

### ISSUE THREAD

**Issue by WZwildwolf** [Byronnar/tensorflow-serving-yolov3#64]
感谢您的贡献，请问输入尺寸（__C.TRAIN.INPUT_SIZE ）的设定是根据什么计算的呢？我的图像是灰度图像，像素值在350*400左右，谢谢！

**Comment by Byronnar** [comment]
你好, 很久没看这个项目了, 你应该完成了吧, 这个设置416就可以了
