### ISSUE TITLE
大佬，为啥mAP(很低)和result(绿柱子比例75%)结果对不上啊

### ISSUE THREAD

**Issue by tiancailin** [Byronnar/tensorflow-serving-yolov3#67]
自己的训练数据，train是4942行，eval是544行（但是这两者里都有一定的重复数据，比如同一个图有3个同位置的框的情况）
warm up和解开所有的层，各自跑了300轮迭代
eval后看mAP只有27.42%，但是Predicted Objects Info.png里看似乎准确率又还可以，这是怎么回事呀？我该相信哪个？
![mAP](https://user-images.githubusercontent.com/6028808/76937693-3e223f80-6930-11ea-87f8-df08da3f1212.png)
![Predicted Objects Info](https://user-images.githubusercontent.com/6028808/76937700-41b5c680-6930-11ea-89db-74e0dd0ba483.png)

**Comment by Byronnar** [comment]
你还修改了什么地方么

**Comment by tiancailin** [comment]
> 你还修改了什么地方么

抱歉打扰了，已确认问题出在哪了。同事写的代码有问题，存在同一个图有多个框的情况，计算map的时候可能hit了一个，其他的没hit到，于是分母变大了。

解决这个问题之后map已经基本正常
