### ISSUE TITLE
你好，config文件中并没有提到2007_val.txt的使用

### ISSUE THREAD

**Issue by xuntan97** [Byronnar/tensorflow-serving-yolov3#69]
经过split之后，数据集被分成三分，train，test，val
我看到config文件中提到了train和test的路径。那么val有没有使用呢，如果没有使用是不是分成test和train就行了

**Comment by Byronnar** [comment]
有啊,有一个验证集, self.test就是可以使用 2007_val, 训练完测试把config文件改成 2007_test用来评估
