### ISSUE TITLE
为什么用了K均值聚类了anchor的大小，为什么map反而掉了0.3个百分点

### ISSUE THREAD

**Issue by tinothy22** [Byronnar/tensorflow-serving-yolov3#70]
用自己聚类出来的anchor比用baseline的anchor反而掉点，是我的数据集太小问题吗，我的数据集只有6120张，两类

**Comment by Byronnar** [comment]
你好,聚类出来的结果不一定有官方的那么好,除非你的数据集 目标分布跟coco voc差别特别大, 而且,6000张图片也不多,聚类不准确也正常.
