### ISSUE TITLE
将产生的saved model文件夹里面的 yolov3 文件夹复制到 tmp 文件夹下面，再运行

### ISSUE THREAD

**Issue by 348872575** [Byronnar/tensorflow-serving-yolov3#75]
你好，在你介绍中的第5步，1.0“将产生的saved model文件夹里面的 yolov3 文件夹复制到 tmp 文件夹下面，再运行”，不知道这个tmp文件夹具体是在哪个位置？我在你的仓库里好像没有找到该文件夹。
2.0 我在conda里配置了你的相关依赖项，但是进行到docker run -p 8501:8501 --mount type=bind,source=/tmp/yolov3/,target=/models/yolov3 -e MODEL_NAME=yolov3 -t tensorflow/serving &指令时出现错误如下：
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

不知道如何在conda里进行复现？

万分感谢

**Comment by 348872575** [comment]
我的微信是a772779281不知道大神能加个微信交流一下吗

**Comment by 348872575** [comment]
tmp文件夹已找到

**Comment by 348872575** [comment]
问题2已解决，在命令前加sudo即可

**Comment by Rezmh** [comment]
> tmp文件夹已找到 
请问下tmp在呢呢

**Comment by 348872575** [comment]
> > tmp文件夹已找到
> > 请问下tmp在呢呢

ubuntu的tmp文件夹
