### ISSUE TITLE
pb文件incompatible with expected float_ref.

### ISSUE THREAD

**Issue by nobody-cheng** [Byronnar/tensorflow-serving-yolov3#77]
你好，我转好pb文件加载的时候
ValueError: Input 0 of node import/yolov3/darknet53/stage0/conv_0/batch_normalization/cond/Assign/Switch was passed float from import/yolov3/darknet53/stage0/conv_0/batch_normalization/moving_mean:0 incompatible with expected float_ref

报了一个float类型的错误，按照网上
![Snipaste_2020-04-23_19-47-09](https://user-images.githubusercontent.com/34908468/80095896-47d83c00-859b-11ea-8c8f-c2dee6df2ff2.jpg)

无法解决

**Comment by Byronnar** [comment]
moving_mean层你放到哪里了

**Comment by nobody-cheng** [comment]
> 
> 
> moving_mean层你放到哪里了
这个已经解决了

**Comment by nobody-cheng** [comment]
对于我修改utils.py
`python
def read_pb_return_tensors(graph, pb_file, return_elements):

    with tf.gfile.FastGFile(pb_file, 'rb') as f:
        frozen_graph_def = tf.GraphDef()
        frozen_graph_def.ParseFromString(f.read())

    with graph.as_default():
        # fix nodes
        for node in frozen_graph_def.node:
            if node.op == 'RefSwitch':
                node.op = 'Switch'
                for index in range(len(node.input)):
                    if 'moving_' in node.input[index]:
                        node.input[index] = node.input[index] + '/read'
            elif node.op == 'AssignSub':
                node.op = 'Sub'
                if 'use_locking' in node.attr: del node.attr['use_locking']
            elif node.op == 'AssignAdd':
                node.op = 'Add'
                if 'use_locking' in node.attr: del node.attr['use_locking']
            elif node.op == 'Assign':
                node.op = 'Identity'
                if 'use_locking' in node.attr: del node.attr['use_locking']
                if 'validate_shape' in node.attr: del node.attr['validate_shape']
                if len(node.input) == 2:
                    node.input[0] = node.input[1]
                    del node.input[1]
                    
        return_elements = tf.import_graph_def(frozen_graph_def, return_elements=return_elements)
    return return_elements`
