### ISSUE TITLE
训练自己的数据

### ISSUE THREAD

**Issue by zhouxianming** [Byronnar/tensorflow-serving-yolov3#8]
你好请问，想要训练自己的数据应该如何部署。自己的数据集的候选框是带有角度的，不像voc那些数据集一样候选框都是水平、垂直的。请问这样需要怎么调整。

**Comment by Byronnar** [comment]
你好，训练好自己的数据之后修改一下 yolov3.py文件里面的48-50行，  将85改成 数据集里面的  类别数+5 ,再用 saved_model.py进行模型转化,就可以生成 saved model格式模型了。
带有角度的框应该也可以直接训练，只是效果可能会比VOC差一些，我还没试过那种数据集。

**Comment by zhouxianming** [comment]
> 你好，训练好自己的数据之后修改一下 yolov3.py文件里面的48-50行， 将85改成 数据集里面的 类别数+5 ,再用 saved_model.py进行模型转化,就可以生成 saved model格式模型了。
> 带有角度的框应该也可以直接训练，只是效果可能会比VOC差一些，我还没试过那种数据集。
感谢回复。在问一下输入是416的话，是要吧尺寸改为13*13吗，请问为什么要这么修改。
![2019-11-06 10-01-08屏幕截图](https://user-images.githubusercontent.com/49632230/68261899-79f0f280-007c-11ea-8012-e7e2287dc17f.png)

**Comment by Byronnar** [comment]
是的，这是因为检测的特征图有32倍的下采样，输入是416*416的话，这里的特征图就是13*13了
13*13*32*32 = 416*416

**Comment by Byronnar** [comment]
是的，这是因为检测的特征图有32倍的下采样，输入是416416的话，这里的特征图就是1313了
13×13×32×32 = 416×416
