### ISSUE TITLE
有关 VOC dataset and yolov3_coco.ckpt 的问题

### ISSUE THREAD

**Issue by ylqi007** [Byronnar/tensorflow-serving-yolov3#81]
你好，楼主，

1. 能麻烦解释下 VOC dataset 的目录结构吗？是把下载下来的`VOCtest_06-Nov-2007` 和 `VOCtrainval_06-Nov-2007`解压后全部放在一个目录下面吗？

2. `yolov3_coco.ckpt` 能解释写到底是预训练数据吗？还是 yolov3 在 coco 数据库上的训练结果？如果要想用其作为预训练数据在 VOC 上进行训练，应该如何做呢？

谢谢
@Byronnar

**Comment by Byronnar** [comment]
你好，这个结构可以参考split.py那个脚本， VOC2007文件里面还有三个文件夹。
yolov3_coco.ckpt可以用作预训练模型，也可以用来作为demo检测
