### ISSUE TITLE
训练后mAP很低该如何调整呢？

### ISSUE THREAD

**Issue by B1D1ng** [Byronnar/tensorflow-serving-yolov3#93]
训练50个epoch后，train-loss是3.5，但mAP很低，训练检测两个类，A类mAP=42.83% B类mAP=8.52%   整体mAP=25左右。。这是为什么呢，同一个训练集下，另一个人用Darknet-yolov4训练完后mAP是94%。。。。
该如何调整？

**Comment by Byronnar** [comment]
首先, yolov3的mAP会比yolov4低, 其次你训练这么低肯定是哪里出问题了, 加载了预训练模型么, batch_size一样么? 还是其他方面
